### ISSUE TITLE
[Bug]: ItemFilters items instead quest item

### ISSUE THREAD

**Issue by fronczek7f** [FTBTeam/FTB-Mods-Issues#1253] opened 2024-07-02 12:40 UTC
### Mod

FTB Quest

### Mod version

ftb-quests-forge-2001.4.6

### Forge / Fabric version

Forge 1.20.1 47.2.21

### Modpack & version

ATM9

### What issue are you having?

After click the quest groups to show quest inside, I see this.
![itemfilters_bug](https://github.com/FTBTeam/FTB-Mods-Issues/assets/17440369/b29ad12f-6626-49d1-b660-15a026cceedf)

I saw this bug reported on ItemFilters git but they send anyone here, also some ppl add ftb compat mod into modpack and for some it work but for me it's not working

Sometime it fixed itself probably after creating new fresh world and next go back to previous

### Crashlogs

[latest.log](https://github.com/user-attachments/files/16068239/latest.log)

### Steps to reproduce

1. Lauch game
2. Enter to world
3. Click on ftb quest icon and it appears

**Comment by desht** [comment] 2024-07-03 10:13
I can't reproduce this (although I have had a couple of reports from people about it before so it looks like a genuine problem, just one I can't track down right now).  It should only happen if the items to be displayed aren't in the creative search tab, but the display code does check and populate the search tab if necessary.

If this does happen again, can you try running `/ftbquests clear_item_display_cache` and see if that helps? You may or may not also need to run `/ftbquests reload`.

**Comment by desht** [comment] 2024-07-03 11:07
Probably same issue as #1127

**Comment by fronczek7f** [comment] 2024-07-04 10:01
Ok, I tested both options and:

The first option with these two commands won't work, it didn't change anything (done this before installing new version)

The second option with the dev snapshot worked, the icons are displayed correctly now

**Comment by desht** [comment] 2024-07-15 15:19
Fixed in FTB Quests 2001.4.7 release

**Closed by desht** 2024-07-15 15:19 UTC
Labels: FTB Quests, 1: Bug
