### ISSUE TITLE
[Bug]: FTB Essentials Home/Warp Crash

### ISSUE THREAD

**Issue by PolyAnthi** [FTBTeam/FTB-Mods-Issues#1011] opened 2023-11-22 22:08 UTC
### Mod

FTB Essentials

### Mod version

ftb-essentials-forge-2001.2.1.jar

### Forge / Fabric version

1.20.1 47.2.0

### Modpack & version

Custom Modpack

### What issue are you having?

I am not sure what causes this random crash but it seems to be doing with warmup, heres command log up to the crash:
```
[22Nov2023 21:57:48.195] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: MR_Blaster issued server command: /home (homename2)
[22Nov2023 21:57:49.905] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Kaut1on_ issued server command: /home (homename)
[22Nov2023 21:57:51.666] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
```

Seems to be when 2 warmups are set off at the same time.

### Crashlogs

Crash log: https://paste.feed-the-beast.com/view/d08eeae2

### Steps to reproduce

Not sure, maybe try running two home warps twice? 
Using warmup: 3 for home config

**Comment by desht** [comment] 2023-11-24 08:37
This is hopefully fixed in the 2001.2.2 release, just out.

(I say "hopefully" since it's not a problem I've been able to reproduce myself, but I've added some extra coding to make the checks as safe as possible. Same fix is in the 1.19.2 version of the mod, and no reports there recently, so hopefully this helps)

**Closed as completed** 2023-11-24 11:26 UTC
Labels: FTB Essentials, 1: Bug
