### ISSUE TITLE
[bug] Quests magically uncompleting and completing. No name collisions.

### ISSUE THREAD

**Issue by Ktanaqui** [FTBTeam/FTB-Mods-Issues#26] opened 2021-08-25 17:45 UTC
To help us help you, please provide as much information as you can, this helps us with debugging and reproducing the issue.

**Mod & Pack version**
ftb-quests-forge-1605.3.3-build.39

**Forge / Fabric version, if applicable**

**Modpack (with version), if applicable**
Stacia Expert, 1.16

**If the issue is a crash; An external link to the crash report**

**How to reproduce the issue**
*Please provide use with a step by step description*
Unknown what's causing the issue; we log off one day, we log on a different day, and the status of the quests have changed.

**A screenshot, if applicable**

**Anything else we should know?**
The behavior is thus: all of my members have, at one point or another, had their quest progress reset completely for no reason whatsoever. Then, some members have _also_ had quests completed for them that they did not complete. There are no naming conflicts or similarities whatsoever. The only people on a team are my husband and I and neither one of us completed the set of quests that were completed for my husband.

**Comment by Raidobw2** [comment] 2022-08-06 02:27
I can confirm that the syncing has been fixed, I've tested it on the latest release of FTB OceanBlock.
And this:
> The only thing I can think is that the last thing I did is to create a FTB team using the chat command.

Now properly keeps your quests as a solo player into your newly created team (it merges correctly). As a result, I'll be closing this since it appears fixed!

**Closed by Raidobw2** 2022-08-06 02:27 UTC
Labels: FTB Quests, MC 1.16+, prio: High ⦿, 2: Feature, state: Fixed :heavy_check_mark:
