### ISSUE TITLE
[Bug]: FTB Backups 2 should not be in the server / client FML mods compatibility checklist list

### ISSUE THREAD

**Issue by mjevans** [FTBTeam/FTB-Mods-Issues#421] opened 2022-08-20 05:02 UTC
### Mod

FTB Backups

### Mod version

ftbbackups2-forge-1.18.2-1.0.11

### Forge / Fabric version

1.18.2 40.1.68

### Modpack & version

Enigmatica 8 - 2.1.0

### What issue are you having?

FTB Backups is removed on the server side due to #314 

The client connect screen displays a scary red X "Incompatible FML Modded Server" "Server mod list is not compatible" message on the _clients_ which do ship with FTB Backups 2.

Why is FTB backups a compatibility breaking mod for this check?  It should safely operate if installed only on the server, without pestering clients.  It should also work for client worlds (on the client) and silently do nothing when the server lacks the mod.

### Steps to reproduce

Install FTB Backups and such on a client.  Have no FTB Backups on an otherwise compatible server.

**Comment by Raidobw2** [comment] 2022-08-21 03:28
> Install FTB Backups and such on a client. Have no FTB Backups on an otherwise compatible server.

Are these the only mods on the server and client?

I'm aware of the ping being truncated, maybe it's that? Courtesy of Freebi85 for explaining this on the DDSS server
![image](https://user-images.githubusercontent.com/17010632/185773990-658c48f9-cb78-4fdb-921b-833e0a4f924e.png)

Modpack authors can use mods like https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker to fix that. Afaik there's another one that can do it, but this one is the one we use in recent packs

Note about removing it from clients: If one removes FTB Backups from the client's mods, people playing Singleplayer will of course no longer be able to automatically backup their worlds. This would affect integrated servers in short

**Comment by mjevans** [comment] 2022-08-21 07:44
> > Install FTB Backups and such on a client. Have no FTB Backups on an otherwise compatible server.
> 
> Are these the only mods on the server and client?

Enigmatica 8 comes with FTB Backup by default, Server AND Client.

To work around the bug wrecking automation on the server (it happened), it is not just disabled (as it was at the time of that event) it is now removed as well.

> 
> I'm aware of the ping being truncated, maybe it's that? Courtesy of Freebi85 for explaining this on the DDSS server ![image](https://user-images.githubusercontent.com/17010632/185773990-658c48f9-cb78-4fdb-921b-833e0a4f924e.png)
> 

Nope: There's a big green checkmark when I run my lan local dev copy of the server.  Users did not report an issue (some didn't even try to connect initially!) until AFTER the event when the mod responsible, FTB Backups, was disabled and that scary X showed up.

**Comment by Raidobw2** [comment] 2022-08-21 07:59
I see, and does removing FTB Backups 2 from clients as well as servers get rid of the red X?

**Comment by mjevans** [comment] 2022-08-21 09:19
I imagine it would, but that's not a solution to my issue.  Clients shipped with the default pack install should work, and since there isn't any requirement for client/server interaction for the mod to work (if there is, it'd be nice to know what that is), it shouldn't advertise as part of the signature for mod compatibility.

**Comment by Raidobw2** [comment] 2022-08-25 00:50
Sorry for the delay, I've managed to look more into this now.

First it's important to understand that FTB Backups 2 only does server side work. As far as I'm aware, there isn't any client specific operations -- the only things you'll see on the client is the chat output, which is sent on the server side, even when playing singleplayer.

I've tested with Rubidium which is a client-only mod, and the green checkmark is shown despite the server not having the mod. I believed this to be caused by this line https://github.com/Asek3/Rubidium/blob/deb88f404fe4a0ea4aff1b380226bb3d97b0cf69/src/main/java/me/jellysquid/mods/sodium/client/SodiumClientMod.java#L39

If we compare it to FTB Backups 2 code, there isn't such thing. https://github.com/CreeperHost/FTB-Backups-2/blob/57be6d5f7e398f709274bdd07c96b09470e4f176/forge/src/main/java/net/creeperhost/ftbbackups/forge/FTBBackupsForge.java#L10-L14.
As said earlier, FTB Backups 2 isn't a client only mod, so that wouldn't work.

However, looking into Forge docs, this should be possible. https://docs.minecraftforge.net/en/1.19.x/concepts/sides/#writing-one-sided-mods however points to the 1.19 constants, but we'll still use it for understanding docs.

> IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
> IGNORESERVERONLY: This tells the client that it should ignore the server version being absent, and the server that it should not tell the client this mod should be present. So this snippet works both for client- and server-only-sided mods.

Both those things would likely prevent any red X on server/client. But you can only set one displayTest property.

Maybe `NONE` can be used instead, or:
> IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.

The 1.18 docs don't fully show the extent of those displayTest properties, but I'll assume they are the same. https://docs.minecraftforge.net/en/1.18.x/concepts/sides/#writing-one-sided-mods

I'll have this reported to the FTB Backups 2 repo and gigabit101 can handle it there as an enhancement

**Comment by Raidobw2** [comment] 2022-08-25 00:54
I've reported this to the main FTB Backups 2 repo, https://github.com/CreeperHost/FTB-Backups-2/issues/26, as a suggestion. To avoid duplicates I'll close this issue. For now you can use the image from Freebi85 above to explain why there is a red X on the server, or E8 can update the mod, which should fix the freezing as well as the current issue with the red X, since you'll be able to put FTB Backups 2 back onto the server.
Cheers

**Closed by Raidobw2** 2022-08-25 00:54 UTC
Labels: prio: Low ◒, FTB Backups 2, MC 1.18+, 2: Feature
