### ISSUE TITLE
[Feature Request]: Track individual quest completion when in a team

### ISSUE THREAD

**Issue by Tisawesomeness** [FTBTeam/FTB-Mods-Issues#1234] opened 2024-06-21 17:48 UTC
### Mod

FTB Quests

### Description

When multiple players are part of the same team, allow quest completion and rewards to be shared across the team, but allow each player to view which quests they have **individually** completed in the quest menu. This enables players to keep track of quests that are important for individual progress / tutorial purposes without leaving the team and losing shared rewards.

### Describe the solution you'd like

Add an icon to quests the player has individually completed in the quest menu. Players can toggle whether they receive notifications for quests the team has completed but the player hasn't completed. There would likely be no notifications by default unless the server changes the default.

### Describe alternatives you've considered

Players can:
- Manually remember / write down completed quests, which is a lot of effort for something the mod can do automatically
- Only claim rewards from quests they have individually completed, though some quest rewards (such as adding XP levels) are better saved for later
- Leave the team, causing other consequences

**Comment by WyFryMU** [comment] 2024-06-24 00:03
Seems somewhat similar to #783 
See this comment specifically: https://github.com/FTBTeam/FTB-Mods-Issues/issues/783#issuecomment-1592565603

**Comment by desht** [comment] 2024-06-24 07:05
It's also a dupe of #1228 

And as stated, this is a highly non-trivial feature. I agree it would be nice, but it needs some redesign of how quests and teams work at a fairly core level of FTB Quests. I'm not ruling it out.

**Closed as completed by desht** 2024-06-24 07:05 UTC
Labels: state: Duplicate :books:

**Comment by Tisawesomeness** [comment] 2024-06-24 14:41
The three issues are similar, but different enough to warrant unique issues
#783 - option for players on a team to not share quest progression across the server
#1228 - option for specific quests to use individual progression instead of team progression
#1234 - team progression works as normal, but individual progress is tracked as well
