### ISSUE TITLE
[Bug]: Visibility not actually blocked?

### ISSUE THREAD

**Issue by TheAngel7** [FTBTeam/FTB-Mods-Issues#1203] opened 2024-05-30 10:55 UTC
### Mod

FTB Quests

### Mod version

2001.4.5

### Forge / Fabric version

Forge 47.2.32

### Modpack & version

Die Hard Forest

### What issue are you having?

When quest is set to this option
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/a263a7c7-0988-4cf2-bce2-37b49b4011ba)
You can still see the tasks/text by right clicking the quests

### Steps to reproduce

1. create a task and lock it behind this option
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/a263a7c7-0988-4cf2-bce2-37b49b4011ba)
2. aim one the quest (it says it's locked)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/8fea070e-a3ee-4851-9796-5275d444a0f3)
3. Right click and it opens up.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/15da427a-552a-488b-85e9-255fac3f9faa)

**Comment by TheAngel7** [comment] 2024-05-30 10:56
in addition those are all other options that might be relevant?
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/6ca4d20e-6675-461e-abfc-a70e0d7f092a)

**Comment by TheAngel7** [comment] 2024-05-30 10:59
I added many question marks, as I don't really know if it's intended or not, if it is you might want to consider rephrasing that.

Since it's not startable because dependencies are not done and yet you can still access and see locked quest's requirements and text

**Comment by desht** [comment] 2024-05-31 10:06
Your screenshot shows that you're still in editing mode; everything is always shown in editing mode.  Does it still show up if you drop out of editing mode (i.e. as a regular player would be) ?

**Comment by TheAngel7** [comment] 2024-05-31 11:36
2. 3. are with edit mode disabled,

And yes you can do it as regular player, in fact my friend told me that he could just do that to see a "locked" quest by just right clicking it, he was on server with same mod version etc. he had no operator permissions, just a regular player

**Comment by TheAngel7** [comment] 2024-05-31 11:40
I just double checked, yes you can do it without editor mode,

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/4e813270-2072-4950-9969-7f2d36f00b44)
*right clicks*
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/eaa8a7a9-5d67-499f-a93c-78391c1b0519)

**Comment by desht** [comment] 2024-06-03 09:49
Is the quest and/or chapter in flexible mode? In flexible mode, that quest would be considered startable, even if it's not completable.

**Comment by TheAngel7** [comment] 2024-06-04 16:38
Progression is set to linear in files
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/2ddc23eb-aff3-4f4e-b44f-4e47fb3ab2ee)

Every chapter/quest uses default (linear)

**Comment by desht** [comment] 2024-06-05 12:53
Then I don't know; I can't reproduce the problem with everything in linear mode.  Clicking an unstartable quest with "Hide Details until Startable" = true doesn not open the quest for me.

**Comment by TheAngel7** [comment] 2024-06-05 15:29
You have to click it with right mouse button.
If still nothing (or you did it already)

Have you tried using my modpack?
Maybe you can replicate it there? or find why that happens.
https://www.curseforge.com/minecraft/modpacks/die-hard-forest
Fastest way to get to the issue would be to just click at the coop quests available from the start.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/89bae9b1-aae0-4b9d-b18d-8055da89b213)
and just click them with right mouse button

**Comment by TheAngel7** [comment] 2024-06-05 15:48
otherwise we could assume it's an incompatibility of some kind

**Comment by desht** [comment] 2024-06-11 10:34
I think I know what's going on now - what I missed is this is about _right-clicking_ the quest.  Should be fixed in the next release.

**Comment by desht** [comment] 2024-07-16 12:56
Fixed in 2001.4.7

**Closed by desht** 2024-07-16 12:56 UTC
Labels: FTB Quests, state: Fixed in Dev 🛠️, 1: Bug
