### ISSUE TITLE
[Bug]: NBT Detection settings not initializing on fresh worlds

### ISSUE THREAD

**Issue by baileyholl** [FTBTeam/FTB-Mods-Issues#684] opened 2023-02-18 17:52 UTC
### Mod

FTB Quests

### Mod version

 ftb-quests-forge-1902.4.8-build.190

### Forge / Fabric version

Forge 1.19.2-43.2.3

### Modpack & version

Arcane Isles

### What issue are you having?

Weak Item NBT detection does not appear to be working on fresh worlds until the task is resaved in edit mode. 

### Steps to reproduce

Create a weak NBT item detection task.
Create a fresh world and attempt to complete the task.

https://gfycat.com/relievednegligibleladybird

**Comment by desht** [comment] 2023-02-20 08:15
Does the entity saved in the item NBT include the entity's position (or any other floating point values) ?

I suspect the problem is floating point comparison imprecision - loading a value from the saved quest on disk gives a value which doesn't test for equality with the actual item being picked up, but re-saving the quest in memory temporarily fixes that.

What does your saved quest look like? (it can be found in `config/ftbquests/quests/chapters/<chapter_name>.snbt`)

**Comment by baileyholl** [comment] 2023-02-20 14:52
The item for detection is simply a tag that contains { entityId:"someId" } and the quest is weakmatch.

The item in hand has complex NBT including a nested BlockEntity tag (containing the entity tag and floating points) and an entityID tag on the top level. Typically these do properly detect after resaving the quest with no changes however, im unsure it is NBT parsing at fault here. I have also tried deleting the Motion fields from the item in hand. 

Quest file: https://pastebin.com/sLZ4hWZD

**Comment by desht** [comment] 2023-02-20 15:45
So looking at the `item` field from e.g. the sheep jar in your quest data, I see:

```
item: {
    id: "ars_nouveau:mob_jar"
    Count: 1b
    tag: {
        entityId: "minecraft:sheep"
    }   
}       
```

Shouldn't that be:

```
item: {
    id: "ars_nouveau:mob_jar"
    Count: 1b
    tag: {
        BlockEntityTag: {
            entityId: "minecraft:sheep"
        }
    }
}
```

?

**Comment by baileyholl** [comment] 2023-02-20 15:48
Nope, I wrote in custom tag data at the surface level because of the previously reported recursive weak search not finding a single attribute in a nested tag, so detection ignores the block entity tag and the item stores a copy of that string at the surface level item tag.

**Comment by desht** [comment] 2023-02-20 16:51
Ah, I see.  OK, putting together a test case to see if I can figure out where the match is falling over...

**Comment by desht** [comment] 2023-03-07 10:34
Fixed in latest Quests release

**Closed by desht** 2023-03-07 10:34 UTC
Labels: FTB Quests, state: Fixed in Dev 🛠️, 1: Bug
