### ISSUE TITLE
[Bug]: [1.18.2+] FTB Ultimine and Hephaestus cannot ultimine at all

### ISSUE THREAD

**Issue by GGG-KILLER** [FTBTeam/FTB-Mods-Issues#512] opened 2022-10-25 18:07 UTC
### Mod

FTB Ultimine

### Mod version

ftb-ultimine:1802.3.3-build.67

### Forge / Fabric version

0.14.9

### Modpack & version

AOF5

### What issue are you having?

Cannot ultimine with a Hephaestus pickaxe at all.

### Steps to reproduce

1. Create a hephaestus pickaxe (in my case it is the one in the image below): ![image](https://user-images.githubusercontent.com/5892127/197843838-8ac7f5a4-9012-43a5-a102-2460683a8ed0.png)
2. Try to ultimine: ![image](https://user-images.githubusercontent.com/5892127/197844026-7fa5dad3-6af9-4f06-8610-83400c3b132b.png)
3. Have the pickaxe mine only a single block: ![image](https://user-images.githubusercontent.com/5892127/197844111-958dddbd-97d9-48d9-b3e8-1156823e66b8.png)

### Anything else to note?

Configuration is the default one:
```
# Configuration for FTB Ultimine that is common to both Clients and Servers
# This file is used to control instance (e.g. modpack) specific things like mod integrations.
# Changes to this file require you to restart the game!

{
	# This is an advanced option, that you better leave alone This will stop ultimining on first block that it can't mine, rather than skipping it.
	# Default: false
	cancel_on_block_break_fail: false
	
	# This will stop mining if tool reaches X durability. It's possible it won't work with special tool types.
	# Default: 0
	# Range: 0 ~ 100
	prevent_tool_break: 0
	
	# Require damageable tools or items added to ftbultimine:tools tag to ultimine.
	# Default: false
	require_tool: false
}
```

For completeness' sake, I have added the tags to the tool through KubeJS:
![image](https://user-images.githubusercontent.com/5892127/197849544-1564fbcb-6402-431b-980a-a935a8640774.png)

**Comment by GGG-KILLER** [comment] 2022-10-28 19:40
It seems there's an entire mod dedicated to fixing this issue: https://www.curseforge.com/minecraft/mc-mods/tamago

**Comment by UnRealDinnerbone** [comment] 2024-07-25 17:55
This should be fixed in newer versions, If it still an issue please let us know

**Closed by UnRealDinnerbone** 2024-07-25 17:55 UTC
Labels: api: Fabric, FTB Ultimine, MC 1.18+, 1: Bug

**Comment by Tunse99** [comment] 2025-01-01 15:43
Hello, sorry to "necro" this but I'm having the same issue on Minecraft version 1.20.1.
Modpack: my own creation (please let me know if you need any information regarding installed mods or such)
Fabric: 0.16.9
Hephaestus Fabric version: 3.6.4.287.jar
FTB Ultimine (Fabric) version: 2001.1.5.jar
The problem is exactly the same as for the OP
Oh, and a Happy new year to you all. :)
