### ISSUE TITLE
[Bug]: Custom Rewards cannot be reset with change_progress command

### ISSUE THREAD

**Issue by TheonlyTazz** [FTBTeam/FTB-Mods-Issues#872] opened 2023-07-14 18:52 UTC
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.15-build.238

### Forge / Fabric version

1.18 / 40.2.0

### Modpack & version

InDev

### What issue are you having?

Created a Custom Reward in FTB Quest. 

wanted to reset it, both methods tested, both failed

- Right click Quest / Reward, reset progress
- Run change_progress Quest on either Quest or Reward

both ended it doing nothing

### Crashlogs

No Crash Logs

### Steps to reproduce

Create a custom reward
Claim it
Try to reset progress
Fail

**Comment by desht** [comment] 2023-07-17 09:46
I can't reproduce this.

* Created a quest (simple item quest with "1 stone") and a custom reward
* Added stone to my inventory, quest completed
* Claimed the reward, "!" icon on the reward was replace by a tick
* Reset the quest via `/ftbquests change_progress @s reset 54ECA05388C039EC`, where 54ECA05388C039EC is the quest ID
* Ticks disappeared from all of quest, task and reward, as expected

Tried same again, except this time cleared by reward ID:
* `/ftbquests change_progress @s reset 3709EF9FDC982ACC`
* Reward icon switched back from a tick to a "!", as expected
* Quest & task remained completed, as expected

**Comment by TheonlyTazz** [comment] 2023-07-17 11:54
I found out why it got bugged,

basicly i was running a KubeJS event that would reset progress on the quest on completion


```
onEvent('ftbquests.custom_reward.7DE54B7F3B3781CC', event => {
  const {player, server} = event
  //do stuff, then reset quest or task
  server.runCommand(`ftbquests change_progress ${player.name.text} reset 7DE54B7F3B3781CC`)	
})
```

adding a server.scheduleInTicks delay made it work.

**Comment by desht** [comment] 2023-07-17 12:45
Ah yeah that will do it.  Think we're OK to close this one then?

**Closed** 2023-07-17 12:46 UTC
