### ISSUE TITLE
[Bug]: Massive Lag Spike When Adding Dependencies To Certain Quests

### ISSUE THREAD

**Issue by itsTort** [FTBTeam/FTB-Mods-Issues#842] opened 2023-06-19 14:54 UTC
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.16-build.235

### Forge / Fabric version

1.19.2 // 43.2.14

### Modpack & version

Custom

### What issue are you having?

Coming to the end of the quests here, I am noticing a massive lag spike (screen freezes and goes white for 2-3 minutes for EACH Dependency added to certain quests). 

This occurs on new/old worlds, and whether I've rebooted my PC or not. 

Testing has been done on a single player world. 

Here is a Spark Profiler of Logging into the world > adding a dependency (as a test) > starting a profiler > adding the same dependency to another quest > freeze for 2-3 minutes > stop profiler:
https://spark.lucko.me/C4BGFTxjsU

Now that I've run the Profiler, I can see my Disk Drive is pretty low, but I don't know if that would be causing the issue, here? 

I want to also say that I just had /too many/ Dependencies assigned or something.  I manually edited from the file to add dependencies in, and while it did successfully apply them, when I went to add another one through FTBQuests, it never recovered after freezing.    To resolve this, I manually removed a bunch of dependencies from the quest series I was working on. 

This seems to only affect when adding a dependency (so far). I am able to add other quests, add rewards, and other quest items/tasks without any issue. 

### Crashlogs

There was no crashes, and here is the Spark log again (https://spark.lucko.me/C4BGFTxjsU).

I am happy to provide any additional resources, please let me know!

### Steps to reproduce

adding a dependency (as a test) > starting a profiler > adding the same dependency to another quest > freeze for 2-3 minutes > stop profiler

However also likely has something to do with the amount of quests I have, and the amount of overall dependencies I have (this is a Progression Modpack spanning 6 ages, and a creative age)

**Comment by desht** [comment] 2023-06-19 15:11
The Spark profile doesn't show very much, and doesn't mention FTB Quests at all.  A freeze like that does kind of suggest you're very low on memory.  Also, manually editing in dependencies to the quest file isn't really recommended.  It's a great way of introducing game-break dependency loops and other corruption...

**Comment by itsTort** [comment] 2023-06-19 15:19
Yeah, it wasn't ideal, but it needed to be tested one way or another, so I can report it properly. 

Upon further testing, it seems to be happening to specific quests.  

I.E, for Age 7, a few (about 8) things were locked behind a T4 Rocket.  Adding the T4 Rocket to anything as a dependency locked things up.  

However, the Base Module (about 20, and I can continue to add more) from Mekanism has tons of dependencies associated with it, and I am able to add that as a dependency to other quests without issue.

**Comment by itsTort** [comment] 2023-06-19 16:15
> 

I'd be happy to do that, but I'm honestly not sure how to do that. I've only ever really used  /spark profiler start/stop. 

What command do I need to run exactly?

**Comment by desht** [comment] 2023-06-19 16:22
IIRC it's just using `/sparkc` instead of `/spark` to force running on the client.

**Comment by itsTort** [comment] 2023-06-19 16:37
This is the results of /sparkc profiler start

https://spark.lucko.me/BvlvO3oEkc

I think it also doesn't show much?  

I did free up system space, and on another instance that I started working off of -- I cleared the dependencies from Age 7 which alleviated the problem (obviously if I add them back it'd come back).

**Comment by desht** [comment] 2023-06-19 16:55
That's still showing the server thread, though?

**Comment by itsTort** [comment] 2023-06-20 03:45
Sorry, I havent been back on the other instance of the server to retest.    

I cleared out a few dependencies in that age, and things returned to normal.     Now, I've stumbled upon a weird issue. 


I have a quest in Age 2 > Tools and a quest in Age 6 > Tech

If I set a quest in Age 2 to a dependency in another part of Age 2 (in this case it was in Age 2 > Tech),  no issues.  However, if I set a dependency to a quest in Age 6 > Tech, I do get a momentary lag spike. 

I believe that if I were to keep adding dependencies there, the problem would return, and adding any dependencies from there would go into a white screen / forever load state. 


I'll try to provide another /sparkc log as soon as possible, when I load the other instance. Maybe I accidentally ran /spark instead of /sparkc.

**Comment by itsTort** [comment] 2023-06-20 15:03
Okay this definitely used /sparkc profiler start/stop

https://spark.lucko.me/5x67mKV3kt

Hopefully it's more helpful than the other. I dont know if it's still showing server, not really sure how to read these.

**Comment by desht** [comment] 2023-06-20 15:09
Yep, that's the client one, thanks.  And yep - I can see a deep hierarchy of calls into the dependency validation code.

You do seem to have a _really_ deep tree of dependencies... can I see your quest file?

**Comment by itsTort** [comment] 2023-06-20 15:28
Yeah, I don't mind sending my ftbquests config file over, I suppose.  I am not sure how to go about that since I don't have the project uploaded to curseforge, yet. 

Until I get a git going, I've been backing up my files and saving them on mega.nz. 

The interesting part with that, I've got some quests that have tons of dependencies (as for instance the Mekanism Module base is a dependent for the rest of the modules).  

The Tier 4 Rocket that I was trying to add though had maybe 10ish dependencies? Not sure the exact count.

**Comment by itsTort** [comment] 2023-06-20 16:18
I setup a temporary Git, and uploaded the afflicted FTB Config to it. 

For reference, the major freeze up occurs when:

Adding a Dependency to Magic or Tech 7 (the specific Dependency was a T4 Rocket from Tech 7). 

Now, as an example -- in Age 3 I have a bunch of Pneumaticcraft upgrades (in Tools 3) locked behind "Pressure Pushing Down On Me" in Tech 3.  No issues at all.

If I attempt to add a Dependency of Tier 4 Rocket from Tech 7, to that same Tools 3 quest, the freeze up does occur.

**Comment by desht** [comment] 2023-06-21 07:54
Can you link me to the temporary repo?  I did accept the invitation but I can't find the link to it anywhere now...

Without actually looking at the book, I'm guessing the sheer complexity of your dependency tree is slowing down the validation process. When a quest is edited, a scan of the quest book is done to ensure that there aren't any looping dependencies, or a dependency depth of >1000, both of which will prevent the edit being committed.  This is done to avoid outright crashes due to infinite or excessive recursion.

I'm surprised though that it hangs for so long - I would have expected not more than a second or so even for extreme cases.  So I'll see if there is a way of alleviating this.  At worst, maybe a just a toggleable setting to enable/disable validation with a suitable accompanying warning...

**Comment by desht** [comment] 2023-06-21 09:43
Update: not to worry, I found the repo and copied it into my dev world (it actually loaded fine despite almost of all of the mods not being present).  Anyway I reproduced your problem and tracked down the cause. Your dependencies are indeed very complex, although valid, and the validation check was running millions of unnecessary checks on quests it had already validated before.

Easy fix, fortunately (just keep track of which quests have already been validated in this run). Now you should find adding dependencies is pretty much instant.

The fix will be in the next Quests release, but if you'd like to test it now, you can try out https://maven.saps.dev/releases/dev/ftb/mods/ftb-quests-forge/1902.4.17-build.241/ftb-quests-forge-1902.4.17-build.241.jar

**Comment by itsTort** [comment] 2023-06-21 15:37
So sorry about that, ended up at the dentist yesterday so I wasn't able to reply here at all to get you the repo. 

Super glad you were able to find it, figure out, and fix the problem!  

I loaded  up that test instance this morning with the new FTB Quests file and everything seemed to work just fine. Was able to instantly add dependencies to that Age that was hanging hard.

Thank you for your time and looking into this!

**Comment by desht** [comment] 2023-07-07 14:37
Fixed in 1902.4.18

**Closed by desht** 2023-07-07 14:37 UTC
Labels: FTB Quests, state: Fixed in Dev 🛠️, 1: Bug
