### ISSUE TITLE
[Bug]: Item task dont get recognized

### ISSUE THREAD

**Issue by TheButterbrotMan** [FTBTeam/FTB-Mods-Issues#279] opened 2022-05-26 18:58 UTC
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1802.3.8-build.101.jar

### Forge / Fabric version

1.18.2 0.14.6 Fabric

### Modpack & version

https://www.curseforge.com/minecraft/modpacks/deathdusk

### What issue are you having?

When i setup a collect 5 diamonds quest, the diamonds gets not recognized in ftb quest, only when i open any kind of container and moving them to another slot. Does not work only in inventar

### Steps to reproduce

1. Create a task with 5 diamonds
2. mine 5 diamonds
3. check ftbquest (not recognized)
4. go to a container(crafting table, chest, etc.)
5. open it and move diamonds to another slot
6. ???
7. diamonds getting recognized

**Comment by desht** [comment] 2022-10-11 12:54
I can't reproduce this problem; I set up a task for 5 diamonds, mined 5 diamond ore, and the task completed, as expected.

It's possible that there's some other mod in that pack which is interfering with how items get added to inventory on pickup, causing FTB Quests not to detect the addition to the player's inventory.  Can you try to reproduce this with a minimal modpack containing only FTB Quests and its dependencies?

**Comment by MichaelHillcox** [comment] 2023-04-08 09:18
No reply, closing

**Closed by MichaelHillcox** 2023-04-08 09:18 UTC
Labels: api: Fabric, FTB Quests, MC 1.18+, 1: Bug, state: Awaiting Reply :speaking_head:
