### ISSUE TITLE
[Bug]: Commands Rewards do not work (minecraft v1.20.1  |-|  FTB Quests v2001.3.0)

### ISSUE THREAD

**Issue by TheExotik** [FTBTeam/FTB-Mods-Issues#1037] opened 2023-12-07 21:32 UTC
### Mod

FTB Quests

### Mod version

2001.3.0

### Forge / Fabric version

Forge 1.20.1 47.2.6

### Modpack & version

Cobblemon Ultra Violet (v1.4)

### What issue are you having?

Commands Rewards do not work with "placeholder"
List of placeholder tested:

> %player%
> %player_name%
> %player_displayname%
> {player}
> {player_name}
> {player_displayname}
> @ p
> @ s

Trying to add a simple command to give "money" to player, but as the "placeholder" wasn't working, i tried to give a simple 
> /give %player% minecraft:diamond

But didn't work as well.

Images:
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/97954441/c9a0b035-faa9-491c-a816-4acd8195e145)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/97954441/731841ee-43e1-48ce-beb8-57bfa06b9127)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/97954441/12680993-bfa6-47a6-821a-9bfec8e52d24)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/97954441/6483d9ca-6344-44f1-a725-189d02682ab4)

### Steps to reproduce

1º Create a simple task to kill [pokemon](https://modrinth.com/mod/cobblemon-quests)
2º Add a "Command Reward" with some command and player placeholder
3º Get the result of "Player not found"

### Anything else to note?

Mohist Build = v1.20.1-527

FTB Library = v2001.1.4
FTB Quests = v2001.3.0
FTB Team = v2001.1.4
Cobblemon Quests = v1.1.5
Cobblemon Mod = v1.4.0

**Comment by TheExotik** [comment] 2023-12-08 18:40
If a pass the actually name of player
Like `/give The_Exotik diamond` this one works

**Comment by desht** [comment] 2023-12-09 09:17
I honestly don't know what you're doing then, because `/give @s diamond` works just fine here, and so does `/give @p diamond`.

**Comment by MichaelHillcox** [comment] 2023-12-09 10:54
To clear this up a bit as I was talking with them in Discord

- They were using give as an example command as they wanted to replace it with the player name
- They want to run a command that gives the player currency, something like `/mod currency give <player> <amount>`
- I've confirmed that with the give command, @s works in dev and on a server in dev but they have confirmed it's not working for them for some reason.
- I've also noted that in 1.20+ the `p` replacement has been commented out? As technically before, it would have been doable for the command to have been something like `/mod currency give {p} 100`

**Comment by desht** [comment] 2023-12-09 10:57
Yeah `{p}` was removed since it's unnecessary, at least under normal circumstances - the standard `@p` and `@s` should always work. But not in this case apparently.

**Comment by MichaelHillcox** [comment] 2023-12-09 10:58
Yeah, that was my assumption. Since the addition of the entity markers and the command being run in the context of the player, the {p} replacement isn't needed. 

We do need to better highlight what replacements are available but that's another matter

**Comment by TheExotik** [comment] 2023-12-09 15:30
Idk if make senses
But the command `/say Hello @p` works (default command)
But any other kind doesn't,  like `/broadcast Hello @p` or `/kill @p`

I gonna make some more tests today.
And yeah, im running in Offline Mode
And also, could be a issue with plugins (none of our plugins should do that I guess, just some for scoreboard, messages, etc...)

**Comment by TheExotik** [comment] 2023-12-10 14:22
Hey, i just have tested and, yeah **ISN'T** something from FTB Quests (Of course is not)

Something with **EssentialsX** plugin, i don't know what is, but if i open the server without this plugin
The command rewards works just fine.

**Comment by desht** [comment] 2023-12-11 08:35
OK, good to know thanks. Running Forge mods with Bukkit-type plugins never works well, and isn't an environment we support for reasons exactly like this. In this case, it looks like these plugins simply don't know how to parse a standard Minecraft command syntax.

Were you aware though, that LuckPerms is available as a Forge mod? 

I guess there's a reason to still support the `{p}` player expansion which was present in older versions of Quests, to work around problems like this. So it can be make available again in future Quests releases (but please don't take this official "support" for Bukkit plugins :smile: )

**Comment by TheExotik** [comment] 2023-12-11 09:48
Yeah...

Yes, luckperms actually have a version to forge, but isn't "compatible" with others plugins... so yeah 🫠.

But thats okay, btw did you know which version still have the `{p}` support? So i can try use and see what happens...
Or i just can play around using others kind of rewards.

**Comment by desht** [comment] 2023-12-11 09:54
You'd need to go back to 1.19.2 for the `{p}` expansion, support was dropped in the 1.20 port.

**Comment by desht** [comment] 2024-01-19 12:44
Fixed in 2001.3.1.  You can use `{p}` again as in 1.19.2, but note that `@p` or `@s` is still the preferred way where possible.

**Closed by desht** 2024-01-19 12:44 UTC
Labels: FTB Quests, state: Fixed in Dev 🛠️, 1: Bug
