### ISSUE TITLE
[Bug]: Three bugs I have noticed in FTB Quests

### ISSUE THREAD

**Issue by DeleteMetaInf** [FTBTeam/FTB-Mods-Issues#492] opened 2022-10-10 02:14 UTC
### Mod

FTB Quests

### What issue are you having?

I’ve experienced three fairly frustrating issues with FTB Quests. In addition to these three bugs, although this one is not a _bug_ per se, it’s quite difficult to add and edit descriptions for quests in-game due to the GUI for descriptions being unintuitive. The message above it does state so and that it’s a temporary solution, but I hope this can be improved upon soon for 1.18.2, as it’s a bit difficult to edit quests in-game when it’s not convenient to add or edit descriptions. Namely, it’s not possible to copy or paste text when editing descriptions, and you can only see part of the text in each line at once, rather than the entire description. Additionally, you can’t add a new line inside a line of text. Say you’ve written a long line in the description of a quest. You can’t split it into two lines.

The fix would be to have the description be one text box instead, which would allow you to copy and paste as well as see the whole description and scroll through it if it’s long, rather than having individual lines that you have to sift through to edit.

FTB Quests is, by far, the best quest mod ever released for Minecraft, don’t get me wrong, but this is the biggest gripe I have with it thus far.

As for the actual bugs:

### Issue 1

Sometimes, seemingly when you’ve reached about four lines in the description of a quest, pressing the enter key takes you to the line above rather than the line below, making it impossible to create new lines unless you edit the chapter file manually and restart the game, which is quite frustrating and makes it difficult to keep working on quests in-game.

**Edit:** I’ve found that this happens even when you don’t have four lines. This has happened to me even when I only have two lines. As Aaron points out below, this turns out to only happen when you _click_ a line and then try to add a new line, but it works fine if you use the arrow keys to select the bottom line instead. It’s still a bug that should be fixed, but at least there is a workaround.

### Issue 2

The files in the FTB Quests config folder do not update when anything in FTB Quests is edited in-game, until the game is saved and exited (or presumably when the world is saved, but I’m not sure). Editing any of the files and then using the `/reload` command does not reload the quests in-game, forcing you to restart the game if you edit anything in the files, which is necessary to do considering the other bugs mentioned in this issue. Considering how long it takes to restart the game in a large pack, this is quite inconvenient.

**Edit:** Duplicate of #483.

### Issue 3

When creating a reward table, every time you add an item to the table, the GUI incrementally shrinks smaller and smaller, until it’s too small to be functional and none of the text is visible—and the buttons quickly become unclickable as well. This is fixed by just clicking “Accept” to exit the menu and then re-enteringing it, but it’s quite frustrating having to do that so many times when editing reward tables in-game.

**Edit:** Duplicate of #360.

#### Issue 1:

Create a quest. Add a description to it. Add several lines until you reach about four. No longer will it be possible to add new lines below the bottom-most line, as new lines are created above it instead.

#### Issue 2:

Edit FTB Quest files in `config\ftbquests` whilst the game is open. The quests will not update in-game until you restart, even if you run `/reload`.

#### Issue 3:

Create a reward table and then add some items to it. You’ll notice that each time you add an item, the GUI shrinks, until it gets too tiny to be usable, forcing you to save and exit the reward table configuration and re-entering the menu to reset the GUI.

****

### Versions:
I am using the latest version of Forge for 1.18.2 as well as the latest versions available on CurseForge of all the mods listed below.

* **Minecraft:** 1.18.2
* **Forge:** 40.1.80
* **FTB Quests:** 1802.3.8-build.101
* **FTB Library:** 1802.3.6-build.140
* **FTB Teams:** 1802.2.6-build.69
* **Item Filters:** 1802.2.8-build.40
* **Architectury:** 4.9.84

**Comment by aaronhowser1** [comment] 2022-10-10 21:54
For the first one, I think that might be when you *click* the line to travel to it, rather than using the up/down arrow keys. Or at least, that causes a similar problem.

**Comment by DeleteMetaInf** [comment] 2022-10-10 23:22
@aaronhowser1 Thank you for the tip! I can confirm, using the arrow keys to select the bottom line rather than clicking it does let you add a new line.

**Comment by manmaed** [comment] 2022-10-12 23:05
Issue 2: #483

**Comment by desht** [comment] 2022-10-13 07:49
Issue 2 is a dupe of #483 and is fixed in dev.
Issue 3 is a dupe of #360 and is fixed in dev.

**Comment by DeleteMetaInf** [comment] 2022-10-13 10:44
@desht That’s great to hear! I can’t wait for the next update. Glad these bugs have been fixed.

As for issue 2, I did note two somewhat distinct issues. One is that the quests aren’t reload when using the `/reload` command, but the other is that the files themselves do not update when you edit quests in game and that you have to save the world in order for them to update. I’m assuming the edited files are stored in a temporary files folder somewhere.

Is the next update also going to fix this, so that you can both edit the files and reload in-game _and_ edit in-game and see the changes occur in the files? If so, that’d be fantastic.

**Comment by desht** [comment] 2022-10-13 15:13
@DeleteMetaInf just to note that the command will be `/ftbquests reload`, not `/reload`.

Regarding saving, Quests currently saves the file server-side (at `config/ftbquests/quests/...`) whenever a world save is done. So when you pause in SSP, or do a `/save-all` on the server.

**Comment by DeleteMetaInf** [comment] 2022-10-13 16:35
Being able to force-save would be a wonderful feature, as you’d be able to edit in-game and then edit the files without exiting the world and re-entering. I hope that can be added.

**Comment by desht** [comment] 2022-11-28 16:33
I think this can be closed now, all fixes are in current 1.18/1.19 releases

**Closed by desht** 2022-11-28 16:33 UTC
Labels: FTB Quests, MC 1.18+, 1: Bug, 2: Feature
