### ISSUE TITLE
[Bug]: FTB Quests's dependency lines are ignoring the visibility of quests

### ISSUE THREAD

**Issue by KrLite** [FTBTeam/FTB-Mods-Issues#610] opened 2022-12-28 09:32 UTC
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1802.3.11-build.151 **but may also happen in other versions**

### Forge / Fabric version

1.18.2 0.17.6

### What issue are you having?

I created two quests: quest A and quest B, and made A both a hidden quest and a dependency for B.

However, when I looked the quest panel, A is hidden well, B is shown, but the dependency line is **still visible,** like this:

<img width="192" alt="image" src="https://user-images.githubusercontent.com/68179735/209787981-1eef9da2-064b-4b43-8e49-9e91c53cbb2c.png">

On the left of the dependency line is quest A but now **hidden,** in my opinion, the dependency line should also be hidden. So I concern that this is a bug.

### Crashlogs

No crashes.

### Steps to reproduce

1. Enable editing mode and create two quests(I'll name them A and B).
2. Set B to `Hide Dependency Lines: False` and mark A as a dependency for B.
3. Set A to `Invisible: True`.
4. Disable editing mode, look at the dependency line from A to B, it still exists!

### Anything else to note?

I'm already having the solution as I've checked FTB Quests's GitHub repo[(I'm using the 1.18 branch).](https://github.com/FTBTeam/FTB-Quests/tree/1.18/main)

Goto `common/../ftbquests/gui/quests/QuestPanel.java`, and guide to `line 207`, [you will see:](https://github.com/FTBTeam/FTB-Quests/blob/031791fd0408bcfc77a078c19e623b5848d4076d/common/src/main/java/dev/ftb/mods/ftbquests/gui/quests/QuestPanel.java#L207)

```java
for (QuestButton button : qb.getDependencies())
```

Well, This sentence iterates all dependencies from `qb`. However, we don't need to iterate them all. Take a look, we don't need to render the dependency line between two quests **if one of them is invisible,** so I changed that line to something this:

```java
for (QuestButton button : qb.getDependencies().stream().filter(QuestButton::shouldDraw).toList())
```

Now it uses `stream` to filter and drops all the quests that are invisible, and won't render the dependency lines between `qb` and the invisible quest. I put it in game and it actually works.

I hope this could be fixed soon whether my solution is feasible. Thanks!

**Comment by desht** [comment] 2023-01-03 13:50
This does look wrong, but I actually can't reproduce the problem:

* Created quest A
* Created quest B
* Add quest A as a dependency of B (so dep arrows point from A to B)
* Mark quest B as invisible
* Mark quest A as do not hide dependency lines

Edit mode on:

![image](https://user-images.githubusercontent.com/736831/210369789-c0867def-a59f-48e2-ae5a-46fd2a8ec32c.png)

Edit mode off:

![image](https://user-images.githubusercontent.com/736831/210369907-4d20ceac-6196-4c90-9dca-df7b9db735a7.png)

Edit mode off, quest selected:

![image](https://user-images.githubusercontent.com/736831/210369996-e94827be-f5d7-4dfb-a75c-4d2d8cd18d25.png)

The final image shows the dependency line, but that is intentional behaviour, to provide a hint to the player that a follow-on quest exists, without revealing any more details about it.

**Comment by desht** [comment] 2023-01-03 13:58
Update: OK, I think I see what's happening here - it's when the _parent_ quest is invisible.  That makes sense, and I think your fix is good.  I'll get it into the next quests release, thanks.

**Comment by desht** [comment] 2023-01-04 11:31
Fixed in latest quests release

**Closed by desht** 2023-01-04 11:31 UTC
Labels: FTB Quests, state: Fixed in Dev 🛠️, 1: Bug
