### ISSUE TITLE
[Question]: FTB Team Islands - Should I lose my items when creating a fresh island on a new server?

### ISSUE THREAD

**Issue by savosdarkran** [FTBTeam/FTB-Mods-Issues#83] opened 2021-10-12 23:03 UTC
### Mod

FTB Team Islands

### Mod version

ftb-team-islands-forge-1605-2.1-build.24

### Forge / Fabric version

1.16.5 36.2.8

### What issue are you having?

When setting up a server and joining.  I spawn on the default lobby island with my starting items.  When I type the command `/ftbteamislands create` the obvious thing happens in that I spawn to the new island.  What I am not sure of is whether or not I should lose my items.

I found in the configuration file that there is a parameter `clearInvWhenTeamLeft = true`.  I expected that this meant that I would lose my items when I leave a team.  So by default am I in a team on my own when I join the server?  If not, is this the expected behaviour for this particular parameter by default?

When I set the parameter to false it works as expected and I spawn on my island with my starting items.

### Steps to reproduce

When clearInvWhenTeamLeft = true
1. setup server
2. configure starting items
3. join server
4. see that starting items are present
5. type /ftbteamislands create
6. spawn on new island with no gear

When clearInvWhenTeamLeft = false
1. Setup server
2. configure starting items
3. join server
4. see that starting items are present
5. type /ftbteamislands create
6. spawn on new island with starting gear

### Anything else to note?

The mod used to give starting items is
starterkit_1.16.5-2.5

**Comment by Raidobw2** [comment] 2021-10-17 07:59
No clue if this could be any useful to you, but in FTB OceanBlock 1.3.0 you can open the modpack folder and find some scripts to add items to your starting inventory. These scripts can be helpful in your own modpack.
In `kubejs/startup_scripts/forgevent.js` precisely.
In-game you can get the item with `/kubejs hand` and then use it in the script.
This uses the mod KubeJS, which is similar to CraftTweaker but for 1.16.
It will make the player spawn with those items on their islands, as seen in OceanBlock for example.

I'll mark your issue as "Bug", but if you ever decide to switch to KubeJS if that works please provide feedback here or close this issue.

**Comment by Raidobw2** [comment] 2021-10-18 00:55
Hmm i see. So you would be giving items before they joined an island.

When you mentioned `clearInvWhenTeamLeft = false` and this behavior:
=>see that starting items are present
=>type /ftbteamislands create
=>spawn on new island with starting gear
Does this mean it worked for you if you set `clearInvWhenTeamLeft` to `false`?
In that case it could be intended behavior from FTB Team Islands to use the config in order to preserve a player's inventory.

If that's not the case and they still lose their inventory regardless, then Michael can fix this.
If that's the case, I'll ask the modder directly anyways since I want to confirm that behavior.

Could you confirm that FTB Teams is installed or not with your game install? Or are you using FTB Team Islands as a standalone?

As for OceanBlock, in KubeJS they use the "island joined" event to give the items, so the items are only given when the player joins their island, not in the lobby/spawn. As KubeJS is commonly used in the suite of mods from FTB (and is also made by our main modder), if you did add FTB Team Islands to that modpack, consider adding KubeJS to get full functionality. That script would be server side only.

Simple example to give the player an apple when they join their island:
```
//Starting items
onForgeEvent("dev.ftb.mods.ftbteamislands.FTBTeamIslandsEvents$IslandJoined", (event) => {
    const player = event.player.asKJS();
    player.give("minecraft:apple");
});
```

**Comment by MichaelHillcox** [comment] 2021-11-05 16:18
So this is intended behaviour, the intention here is to clear the players inventory when they change team as it would break progression on other peoples islands when you switch. You can disable this if you want from the config you have changed to get your desired effect. 

The reason it's clearing your inventory in your case is because FTB Teams has 3 different team types, player team, an actual team and a server team. The player team being just you. So when you join the server, you're automatically a player team, thus when you join a new team (create a new island) your inventory is wiped.

I'll wait for feedback on @Sunekaer if this functionality should be modified in anyway. The KubeJs solution looks ideal but doesn't work well with the mod you use. I'd recommend not using that mod and use the event that @Raidobw2 has shown.

**Comment by savosdarkran** [comment] 2021-11-05 17:05
@MichaelHillcox This makes sense and the answer I was expecting.  I appreciate you clarifying.  I feel this issue can be closed but I will leave that up to Sunekaer.

Take care.

**Closed** 2021-11-05 17:21 UTC
Labels: Bug, FTB Team Islands
