### ISSUE TITLE
[Bug]: FTB Chunks fullscreen map causes client freeze/lock unrecoverable

### ISSUE THREAD

**Issue by RobertSnype** [FTBTeam/FTB-Mods-Issues#622] opened 2023-01-07 18:09 UTC
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.4-build.220

### Forge / Fabric version

43.1.55

### Modpack & version

All the Mods 8-1.0.7

### What issue are you having?

Zooming out in fullscreen map on multiplayer causes CPU/Ram to max out and lock client. Game works fine on this lower end PC, but when zooming out loading the map slows and eventually causes lock. Continues to get worse if/when I can close out of map. Must disconnect if lucky or more commonly kill via cmd. No recovery even if zooming out a little.

### Crashlogs

No log due to lock up

### Steps to reproduce

Log into multiplayer (I use atm8-2), press "E". Open fullscreen map in top left. zoom out quickly while monitoring CPU/Ram usage. Client starts freezing.

### Anything else to note?

This really sucks as the only time I use the zoomed out map is while exploring. I'm still alive but the client doesn't allow me to disconnect. During that time, I usually die or drown on the server. I've died a lot due to this and stepped away for a while because of the frustration it causes.

**Comment by desht** [comment] 2023-01-13 12:30
Can you please supply as much detail as possible about your system specs (memory & CPU in particular) ?

**Comment by KAMKEEL** [comment] 2023-01-20 09:21
Hello! I believe this crash has to do with the same issue I've been experiencing when pressing the Fullscreen Button for FTB Chunks (1.19.2) latest version (forge).

Here is a paste of the crash. [Pastebin](https://pastebin.com/GFcPQYrM)

Not sure if it's related, but this seems to be 100% consistent for anyone trying to open the map. (Also the minimap does not render either)

**Comment by desht** [comment] 2023-01-20 09:24
@KAMKEEL this issue has nothing to do with your problem, which is completely different.  Please don't hijack issues like this.

**Comment by KAMKEEL** [comment] 2023-01-20 16:17
> @KAMKEEL this issue has nothing to do with your problem, which is completely different. Please don't hijack issues like this.

@desht Sorry! I couldn't tell if it was related or not, not my intentions to hijack a report :(

**Comment by legitswitch** [comment] 2023-01-21 02:41
Is this on a multiplayer server with hundreds or even thousands of different claims?

**Comment by MichaelHillcox** [comment] 2023-02-12 10:22
Duplicate of #616

**Closed by MichaelHillcox** 2023-02-12 10:22 UTC
Labels: api: Forge, FTB Chunks, MC 1.16+, state: Awaiting Reply :speaking_head:
