### ISSUE TITLE
[Feature Request]: Change the Search Keybind

### ISSUE THREAD

**Issue by FooterMan15** [FTBTeam/FTB-Mods-Issues#855] opened 2023-07-02 22:38 UTC
### Mod

FTBQuests

### Description

I'm really not sure if this is a waste of time, but I've found that holding `shift` opens a Search box, but that causes disruption when holding `shift` on Tasks in a Quest for more information if available on the tooltip. And I'm not sure if I'm just blind, but I couldn't find a way to change the keybind for it in the mod's GUI, Config, or Controls menu.

### Describe the solution you'd like

Add a way to modify the keybind, and make it default to something other than `shift`.

**Comment by desht** [comment] 2023-07-04 07:34
I've seen this reported before, but I can't find the related issue now. In any case, this is happening because of a problem with your keyboard, basically. Pressing and holding Shift (or any modifier key like Ctrl or Alt) _should_ send a keypress event and nothing else; other keys will send repeated keypress and keyrelease events. But your Shift key is sending repeated press/release events, and it should not be.

You can see this behaviour with a debugging app like https://w3c.github.io/uievents/tools/key-event-viewer.html - try pressing and holding Shift and see if you get just one press event, or a whole stream of events.

As for why it's happening, I'm not sure.  But modifier keys should never behave this way.

**Comment by desht** [comment] 2023-07-05 15:32
Having discussed this with the team, we're going to remove the double-tap Shift to search in the next FTB Quests release.  I should note that Ctrl+F already works to open the search window, and that will become the only way to do it.

**Comment by desht** [comment] 2023-07-07 14:37
Fixed in 1902.4.18

**Closed by desht** 2023-07-07 14:37 UTC
Labels: FTB Quests, 2: Feature

**Comment by death587** [comment] 2024-10-15 23:57
im a year late but i found the cause. check if you filter keys is off turning it on fixed this for me.
