### ISSUE TITLE
[Bug]: Delightful dirt only spawns Drygmy´s

### ISSUE THREAD

**Issue by Shimdak** [FTBTeam/FTB-Mods-Issues#322] opened 2022-06-23 11:06 UTC
### Mod

Ars Nouveau-Mob Grinding Utils

### Mod version

Direwolf20 1.18 pack vers 1.6.0

### Forge / Fabric version

Forge 40.1.52

### Modpack & version

Direwolf20 1.18 vers 1.6.0

### What issue are you having?

Delightful dirt from Mob Grinding Utils only spawns the Drygmy mob from Ars Nouveau

### Steps to reproduce

Create delightful dirt by clicking Golden egg on dirt

**Comment by TheonlyTazz** [comment] 2022-06-23 11:54
not an FTB Mods issue, this needs to be placed in the FTB Modpack issue tracker which would then be a duplicate of:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/912
this issue can be closed

**Closed** 2022-06-24 08:23 UTC
