### ISSUE TITLE
[Bug]: FTB Chunks Fails to Load

### ISSUE THREAD

**Issue by MrXodus** [FTBTeam/FTB-Mods-Issues#712] opened 2023-03-11 02:30 UTC
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge:1902.3.17-build.244

### Forge / Fabric version

1.19.2

### What issue are you having?

FTB Chunks fails to load properly on start up

### Crashlogs

[crash-2023-03-10_16.24.12-fml.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10947387/crash-2023-03-10_16.24.12-fml.txt)

### Steps to reproduce

1. I start up minecraft using CurseForge and it crashes

**Comment by desht** [comment] 2023-03-11 08:52
1. Dupe of #707
2. Not a Chunks issue.  Complain to the author of Merchant Markers at https://github.com/AHilyard/MerchantMarkers/issues/21 who has no business mixing into Chunks code like this.

**Closed** 2023-03-11 08:56 UTC
