### ISSUE TITLE
[Bug]: Unexpected error

### ISSUE THREAD

**Issue by TheButterbrotMan** [FTBTeam/FTB-Mods-Issues#659] opened 2023-01-31 00:06 UTC
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.12-build.217.jar  

### Forge / Fabric version

1.18.2 40.1.93

### Modpack & version

Draconia Unleashed

### What issue are you having?

According to a player of the modpack his mini map disappeared, also the cords under it. When he trys to open a big version/or pressing m key it crashes.

"My mini map disappeared, as did the cords under it, and if i try and open a big version, from my inventory or the m key it crashes my game"

### Crashlogs

https://bytebin.lucko.me/KSVzyGBhTH

### Steps to reproduce

Im not sure tbh. Seems to be a weird interaction

**Comment by desht** [comment] 2023-01-31 08:29
This is a problem with server chunk & map data not being sync'd to the client.

* Is your server in offline mode?
* Did this work for the player previously, and suddenly stop?  If so, was anything changed in terms of mods being added or upgraded?

**Comment by MichaelHillcox** [comment] 2023-02-12 10:21
Duplicate of #616

**Closed** 2023-02-12 10:21 UTC
Labels: api: Forge, FTB Chunks, MC 1.18+, state: Awaiting Reply :speaking_head:
