### ISSUE TITLE
[Bug]: FTB Chunks Map closes world

### ISSUE THREAD

**Issue by itsjusttriz** [FTBTeam/FTB-Mods-Issues#653] opened 2023-01-25 17:06 UTC
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.115

### Forge / Fabric version

1.16.5 36.2.34

### Modpack & version

Harvestblock-2.1.0b

### What issue are you having?

Noticed my minimap had disappeared (*was previously visible, not sure what happened*) So I used `m` to toggle it... then i got booted from my world.. Pack didnt crash though.

Went back into my world and tried again... same thing.

Then tried opening the map from the icon on top-left of my inventory.. same thing, but with a log link this time.

### Crashlogs

https://bytebin.lucko.me/MG3pLTsEW0

### Steps to reproduce

No idea honestly. Something to keep an eye on, maybe?

**Comment by MichaelHillcox** [comment] 2023-02-12 10:21
Duplicate of #616

**Closed by MichaelHillcox** 2023-02-12 10:21 UTC
Labels: api: Forge, FTB Chunks, MC 1.16+
