### ISSUE TITLE
[Bug]: pressing map key opens map while typing in a text field

### ISSUE THREAD

**Issue by Keltas** [FTBTeam/FTB-Mods-Issues#591] opened 2022-12-13 18:59 UTC
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.10-build.210

### Forge / Fabric version

1.18.2 40.1.86

### What issue are you having?

Pressing open map key (default "m") force opens map even when you are typing in a text field. This makes it impossible to use the key while typing. 

I've tested it by installing just Forge and FTB through curseforge (which installed other prerequisites) and was able to reproduce it without other mods.

### Steps to reproduce

1. Start typing eg. by pressing "/".
2. Type what you wish to type including the default letter "m" for example gamemode.
3. The moment you press "m", the map opens preventing you from finishing the command.

**Comment by desht** [comment] 2022-12-14 08:21
Confirmed... oops.  Will get a fix out for that.

**Comment by desht** [comment] 2022-12-14 15:22
Fixed in 1802.3.11 release

(Note that the issue isn't present in the current 1.19.2 release, only 1.18.2 was affected)

**Closed by desht** 2022-12-14 15:22 UTC
Labels: api: Forge, FTB Chunks, MC 1.18+
