### ISSUE TITLE
[Bug]: FTBIC Incompatible with AllTheOres

### ISSUE THREAD

**Issue by TheLMiffy1111** [FTBTeam/FTB-Mods-Issues#263] opened 2022-05-15 17:27 UTC
### Mod

FTB Industrial Contraptions

### Mod version

ftb-industrial-contraptions-1802.1.4-build.139

### Forge / Fabric version

1.18.2 40.1.19

### What issue are you having?

Upon world creation, the game crashes due to a feature cycle. This seems to be because FTB Industrial Contraptions and AllTheOres registered ore generation features with the same name.

### Crashlogs

Crash report from dev environment: https://pastebin.com/AuwTKwe5

### Steps to reproduce

Install FTB Industrial Contraptions and AllTheOres and create a new world.

**Comment by Raidobw2** [comment] 2022-05-29 07:24
Hmm, I'm unsure if this is the fault of FTB IC, but one of our mod developers will have a look. It could be good to have this reported on ATM's side as well

**Comment by TheLMiffy1111** [comment] 2022-05-29 09:00
I reported this issue on both issue trackers

**Comment by jeremiahwinsley** [comment] 2022-05-29 17:30
I don't see an issue on the ATO tracker for this, but this is likely our bug as we are looking into a similar issue with another pack. 

That said, FTBIC and ATO do work fine together in ATM7, so it may be one of your other mods that is conflicting rather than FTBIC.

**Comment by Raidobw2** [comment] 2022-05-29 19:26
Ah, then it makes more sense that the Cyanide mod is actually causing an issue. Remove it from the mods folder and that should work https://www.curseforge.com/minecraft/mc-mods/cyanide-forge

**Comment by TheLMiffy1111** [comment] 2022-05-29 19:30
I installed Cyanide because of the crash, here's the crash report before I installed Cyanide:
https://pastebin.com/EuDF20c3

**Comment by Raidobw2** [comment] 2022-05-29 19:36
Were you able to reproduce the crash only with FTB IC  and ATO? That crash still presents other mods, which should be removed when testing for incompatibilities

**Comment by TheLMiffy1111** [comment] 2022-05-29 19:48
Crash report with only FTBIC, ATO, and Myrtrees
https://pastebin.com/Xntqpwbh

**Comment by jeremiahwinsley** [comment] 2022-05-29 22:41
We were able to track down what seems to be the issue here: https://github.com/AllTheMods/AllTheOres/pull/26

As OP mentioned, ATO and FTBIC both register their features in the vanilla namespace, instead of using the mod namespace. Moving ours to the correct namespace fixes the overlap, you may want to do the same for FTBIC.

**Comment by MichaelHillcox** [comment] 2022-07-29 14:56
Fixed as of the above PR, releasing later today :+1:

**Closed** 2022-07-29 14:57 UTC
Labels: Bug, FTB Industrial Contraptions
