### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Orangejewce92** [FTBTeam/FTB-Mods-Issues#567] opened 2022-12-06 01:34 UTC
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.8-build.199.jar

### Forge / Fabric version

forge 1.18.2 40.1.86

### What issue are you having?

After updating all the ftb mods for 1.18.2 i can not log into my server i receive a message that states: ams:team (bunch of weird text) brigadier:integear(weird text) bypass_protection(weird text) extra_claim_chunks(weird text)extra_force_load_chunk 

and lose connection. 
single player is fine.

### Steps to reproduce

1. updated the mods.
2. stepped down the mods and everything was fine.
3. unsure what changed ( i am using ftbranks and allotting claim chunks per rank.

**Comment by desht** [comment] 2022-12-06 08:32
That sounds like a network sync problem indicating that you probably have different versions of the mods on client and server.  Please verify you have identical versions on both sides.

I have tested connection to dedicated server (with matching versions of course), and there is no problem in connecting.

**Comment by Orangejewce92** [comment] 2022-12-06 11:43
Hello, thanks for the reply! I did indeed verify that I had the same versions on both sides.

**Comment by Orangejewce92** [comment] 2022-12-06 11:53
New worlds the mods work fine. I believe it to be something with existing worlds that causes issues. 
I'm okay with Wiping the claims. Which I tried by deleting the FTBchunks folder in world folder. Still same issue. I even removed the ranks with granting claim and force load still same issue. Unsure if maybe it's a rank to chunk bug?

**Comment by desht** [comment] 2022-12-06 12:35
It's more likely to be the team data than the chunk data (i.e. in `world/ftbteams`), from looking at your error.

Is this happening when the player connects?  Is there anything relevant in your server log when the connection is lost?  Or client log?

**Comment by desht** [comment] 2022-12-06 12:39
Also, a screenshot of the *exact* error text would be very useful.

**Comment by Orangejewce92** [comment] 2022-12-06 14:07
![image](https://user-images.githubusercontent.com/110748022/205933753-60cdcaee-7a1f-47f9-a884-309f6339455d.png)

**Comment by Orangejewce92** [comment] 2022-12-06 14:30
Hope this helps

**Comment by desht** [comment] 2022-12-06 14:46
Can I get a copy of your ftbchunks folder?  Going to need to find a way of reproducing this problem, since I can't make it happen here...

Can you also post the versions of all FTB mods, on both the client and server side?

**Comment by Orangejewce92** [comment] 2022-12-06 15:18
ftb-chunks-forge-1802.3.8-build.199.jar

ftb-ranks-forge-1802.1.9-build.58.jar( ranks is only server sided)

ftb-teams-forge-1802.2.8-build.78.jar

ftb-library-forge-1802.3.8-build.163.jar

ftb-essentials-1802.1.7-build.42.jar(essentials is only server sided for my pack )

https://mega.nz/file/na5lXYZT#NLyCmyZmaouMkJSMJAP_qTybyUIzy95I4iheD-FpWwE
^ FTBchunks folder

**Comment by Orangejewce92** [comment] 2022-12-06 16:21
So ranks is now dependent. Is this confirmed? When I get home tonight I will test !

**Comment by Orangejewce92** [comment] 2022-12-07 00:48
Great! am home and all works fine!
BUT!
Item sharing in chat no longer works (works on previous version of FTBranks.
(i believe it is a quark ability) where you could share any item in chat to display what it is.
Updating to newest and latest version seemed to only display the name and not the item.


![image](https://user-images.githubusercontent.com/110748022/206060076-f8092924-1044-4b5a-a9bf-790c6a2d013a.png)

**Comment by desht** [comment] 2022-12-07 09:30
Yeah, you're right. That'll be fixed in the next release, hopefully today.

**Comment by desht** [comment] 2022-12-07 12:03
https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-forge/files/4141695 fixes this (and should also complain if you forget to install Ranks on the client...)

**Closed by desht** 2022-12-07 12:03 UTC
Labels: FTB Ranks, state: Fixed in Dev 🛠️, MC 1.18+, 1: Bug

**Comment by sauramel** [comment] 2022-12-09 05:23
Was making quark item linking work really more important than having FTBRanks work as a server side only mod? this seems counter productive.

**Comment by Orangejewce92** [comment] 2022-12-09 15:09
The latest release fixed item sharing. I appreciate the hard work.

**Comment by Orangejewce92** [comment] 2022-12-09 15:10
Also can I make a datapack to update the interact blacklist ? For (chunks) I've just been adding to the jar server side and that works but I just thought this morning I think I could make a datapack lol.

**Comment by desht** [comment] 2022-12-09 15:25
Do you mean items which are blacklisted from use?  If so, yes you can use a datapack to add items to the `ftbchunks:right_click_blacklist` item tag.  Normal datapack rules apply, all documented at https://minecraft.fandom.com/wiki/Data_pack

**Comment by Orangejewce92** [comment] 2022-12-09 15:43
Sweet! It would be cool to see a serverconfig to add to the interact list but a datapack is ez pz

**Comment by sauramel** [comment] 2022-12-12 02:33
> The two features are completely unrelated. Just happen to be both in the same release. FTB Ranks now needs to be on the client too because it supports tab-completion for its command-line.

This is an awful change, you have taken away a feature that allowed server hosts to integrate this mod into just about any pack, Many of the largest packs include no FTB mods and many will not update to include this. This is a permissions mod, for servers. This change is fundamentally flawed.

**Comment by oliviajumba** [comment] 2022-12-12 03:18
> Yes, you will definitely need Ranks on the client too. Next version of Ranks will not be marked as server-only anymore (forgetting to do that for this release was my mistake, sorry), so you'll see the mismatch at the login screen.

Well that's stupid. Many players are not going to want to download an extra client-side mod on top of the modpack, and many modpacks will not add this mod. Please revert back to how it was before!

**Comment by bugescape** [comment] 2022-12-12 09:17
> The two features are completely unrelated. Just happen to be both in the same release. FTB Ranks now needs to be on the client too because it supports tab-completion for its command-line.

This record breaking retardness in FTB dev is pushing your reputation into the bin

Fuck you

**Comment by desht** [comment] 2022-12-12 09:27
@sauramel yes, that's a compelling argument, and I will back this change out.  I was just trying to improve usability from a server admin point of view, but I agree this is more disruption than it's worth.

On the other hand, any swearing or abuse (not looking at you, sauramel) will absolutely not be tolerated.

**Comment by MaxNeedsSnacks** [comment] 2022-12-12 09:34
We could most likely just use custom suggestions to achieve a *similar* effect to what the rank argument type would've done, but it means validation wouldn't be happening in real time unfortunately

**Comment by emibanana** [comment] 2022-12-12 09:53
>
> @sauramel yes, that's a compelling argument, and I will back this change out. I was just trying to improve usability from a server admin point of view, but I agree this is more disruption than it's worth.
> 
> On the other hand, any swearing or abuse (not looking at you, sauramel) will absolutely not be tolerated.

Can you at least suggest a mod that is similar so ppl that want to move away from FTB has an option as we have enough with FTB development bullshit

**Comment by emibanana** [comment] 2022-12-12 09:55
wrong reply, should be @desht

**Comment by MichaelHillcox** [comment] 2022-12-12 10:00
FTB Development Bullshit? I'd love to know how you justify this comment. The change was not intended to make anyone's experience worse, and we've been receptive to the feedback and from my understanding, we're reverting it back to be server side only.

You can google alternatives. Nobody is forcing you to use our mods.

**Comment by desht** [comment] 2022-12-12 10:13
I added a feature which I thought would be helpful.  Turned out the negatives outweighed the positives, and the feature is being rolled back, because I listened to the (non-abusive) arguments.  If you don't like that, you're entitled to a full refund.

**Comment by MichaelHillcox** [comment] 2022-12-12 10:19
Please feel free to email goaway@feed-the-beast.com for your full refund. Locking this thread.
