### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LPDMinecraft** [FTBTeam/FTB-Mods-Issues#82] opened 2021-10-12 19:07 UTC
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-forge-1605.3.0-build.25

### Forge / Fabric version

Forge 1.16.5 36.2.8

### Modpack & version

Create Live IV (my own)

### What issue are you having?

When I mine at Andesite, it dont mines only the andesite. It mines the andesite and the stone

### Crashlogs

I dont have any Crashens

### Steps to reproduce

1. Download Modpack
2. Go into World
3. Get Wood
4. Craft Pickaxe
5. Press ^

### Anything else to note?

No

**Comment by Raidobw2** [comment] 2021-10-17 08:07
That is correct, closing this as it is intended behavior. Use the config option provided by DreamingLamb.

**Closed by Raidobw2** 2021-10-17 08:07 UTC
Labels: Bug, FTB Ultimine
