### ISSUE TITLE
[Bug]: Quests 1.3.1 missing convert to tag item option

### ISSUE THREAD

**Issue by TheShadowModsUK** [FTBTeam/FTB-Mods-Issues#1085] opened 2024-01-26 19:35 UTC
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.2

### Forge / Fabric version

1.20.1 - 47.2.0

### What issue are you having?

1.2.1 had the option to use/convert to tags but no where in the change long do I see it saying it's been removed but now it's now longer there it's missing and older already set tags just how so a filter image rather then the icons looping like it used to, but no option to add a new one ever.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/90859294/0af55151-e1f4-4b7c-9133-875a207b6906)

I am now stuck and I can't see no change log, the wiki just opens a discord server, is this a change or is a bug

### Steps to reproduce

install ftb-quests-forge-2001.3.2
enable editing mode
add new item task
add item
right click to convert

Missing convert option

**Comment by tehgreatdoge** [comment] 2024-01-28 21:38
It seems like quests also don't display existing tag filters anymore.

**Comment by desht** [comment] 2024-01-29 08:33
Duplicate of #1081.  Update FTB XMod Compat to latest release.

**Closed by desht** 2024-01-29 08:33 UTC

**Comment by todorolo** [comment] 2024-02-09 18:51
bumping this,
It is not a duplicate of #1081, that one is trying to get quests to recognize items inside OR filters. This issue is that there's no option to convert an item to the tag.

**Comment by desht** [comment] 2024-02-09 22:46
Install the latest releases of both FTB Quests and FTB XMod Compat.  Then just right click on any item task in the quest view panel, and select the "Convert to Item Tag" option.  That is all.

**Comment by bangplaysgames** [comment] 2024-03-15 14:09
I'm having the same issue.  I have the most recent versions of both FTB Quests and FTB XMod Compat.  

ftb-quests-2001.3.3.jar
ftb-xmod-compat-2.1.0.jar

**Comment by desht** [comment] 2024-03-15 15:21
Make sure you also have Item Filters and/or FTB Filter System mods installed.

**Comment by VexLeviathan** [comment] 2024-06-10 21:28
I have updated item filter to the most recent version, same with ftb quests and ftb xmod compat. Im on 1.19.2 and i cant find a ftb filter system mod for this version. Still cant find the conver to tag item option

**Comment by desht** [comment] 2024-06-11 14:04
FTB Quest 1902.5.9  (1902.5.8 also verified working)
FTB XMod Compat 1.2.4
Item Filters 1902.2.9

It works fine:

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/736831/1b876133-8c2c-4a60-97f7-9a52788dfea6)
