### ISSUE TITLE
[Bug]: Essentials CME multiple people using command with warmup

### ISSUE THREAD

**Issue by phit** [FTBTeam/FTB-Mods-Issues#982] opened 2023-10-22 12:48 UTC
### Mod

FTB Essentials

### Mod version

ftb-essentials-forge-2001.2.1.jar 

### Forge / Fabric version

1.20.1-47.1.3

### Modpack & version

ATM9

### What issue are you having?

I believe this happens because we have the /home or /spawn command configured to use a warmup, when then multiple players use either command at the same time this crash happens.

### Crashlogs

https://gist.github.com/phit/2f3881150c7967418e510ab150082cf2

### Steps to reproduce

enable command warmup for /home, have multiple people running the command at the same time on a server

**Comment by desht** [comment] 2023-10-25 08:03
I can't reproduce this one myself (tried on a server with two players simultaneously using warmups) but I've pushed a change which may help?  This will be in the next Essential release, in the next day or so.

**Closed** 2023-11-30 15:50 UTC
Labels: FTB Essentials, 1: Bug
