### ISSUE TITLE
[Bug]: Client Side Crashing

### ISSUE THREAD

**Issue by UTCrown** [FTBTeam/FTB-Mods-Issues#875] opened 2023-07-16 14:07 UTC
### Mod

FTB Chunks

**Comment by desht** [comment] 2023-07-17 09:18
Please don't post huge stacktraces directly into an issue!  Paste sites like https://paste.feed-the-beast.com/ exist for a reason, please use them.

**Comment by desht** [comment] 2023-07-17 09:29
Anyway, the problem is Optifine, which for some bizarre reason is causing a Forge mob griefing event to be fired _on the client_.

I can work around this in the next release of FTB Chunks, but the best fix is to uninstall Optifine, and use better mods like Rubidium/Oculus.

**Comment by desht** [comment] 2023-07-20 11:28
Fixed in 2001.1.4 release
https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/4654814

**Closed by desht** 2023-07-20 11:28 UTC
Labels: FTB Chunks, state: Other Mod, 1: Bug
