### ISSUE TITLE
[Bug]: FTB breaks Quarks item formatting

### ISSUE THREAD

**Issue by Darkere** [FTBTeam/FTB-Mods-Issues#122] opened 2021-11-20 15:30 UTC
### Mod

FTB Ranks/Teams not certain

### Mod version

ftb-ranks-forge-1605.1.5-build.16.jar, ftb-teams-forge-1605.2.3-build.38.jar

### Forge / Fabric version

36.2.9

### What issue are you having?

![image](https://user-images.githubusercontent.com/4283717/142732061-dd49da5e-dac6-47d6-8e8c-8763fbf81106.png)

### Steps to reproduce

share item in chat

**Comment by Raidobw2** [comment] 2021-11-22 09:17
I can confirm it's FTB Ranks, since removing the mod allows the preview to render again.

**Comment by jinkhya** [comment] 2022-02-26 12:22
Oh I was gonna report this but I see it already has. I'm also encoutering this issue. 
This is what quark sharing item refers to : https://github.com/VazkiiMods/Quark/blob/1.16.5/src/main/java/vazkii/quark/content/management/module/ItemSharingModule.java

I hope it's something that can be fixed :)
Thanks in advance !

**Comment by Gbergz** [comment] 2022-03-21 16:51
Also just encountered this issue, glad it's reported already.

**Comment by Shadows-of-Fire** [comment] 2022-05-15 23:19
This is a bit more than just quark being broken - the style of ALL messages is being voided if FTBRanks is doing name formatting.  This is caused by using a TextComponent here https://github.com/FTBTeam/FTB-Ranks/blob/main/common/src/main/java/dev/ftb/mods/ftbranks/impl/FTBRanksAPIImpl.java#L90 and can be fixed by doing concatenation with nested TranslatableComponents, which preserve the style of their children components.

**Comment by MichaelHillcox** [comment] 2022-05-17 08:19
I’ll sort this

**Comment by X-Niter** [comment] 2022-05-21 23:49
# Temperrary option for you awesome people
https://github.com/X-Niter/FTB-Ranks/releases/tag/ftb-ranks-forge-1605.1.5-build.666

Just got done fixing it for 1.16.5 and tested it with ATM6/E6 and E6E server. (Moving forward to 1.18.2)
Subjective to your feelings of course :)

**Comment by MichaelHillcox** [comment] 2022-05-22 01:38
You can't redistribute our mods... make a pr

**Comment by MaxNeedsSnacks** [comment] 2022-05-23 00:13
> This is a bit more than just quark being broken - the style of ALL messages is being voided if FTBRanks is doing name formatting. This is caused by using a TextComponent here https://github.com/FTBTeam/FTB-Ranks/blob/main/common/src/main/java/dev/ftb/mods/ftbranks/impl/FTBRanksAPIImpl.java#L90 and can be fixed by doing concatenation with nested TranslatableComponents, which preserve the style of their children components.

Looking into this a bit, it seems like a good chunk of this code is from the FTB Utilities days :see_no_evil: For now, #27 / #28 should represent a best effort fix if no other mod *substantially* modifies the chat format, which, if they do, players should just disable the FTB Ranks format in my opinion, but it should definitely work with things that just append to the main message like Quark

**Comment by MaxNeedsSnacks** [comment] 2022-05-23 00:21
Also, the goal of this isn't *just* to allow name formatting, but to format the entire chat message as well (to allow for `&6coloured` messages, for instance), which is part of why we need to look at the *entire* message rather than just the "prefix" (which are both part of the same Component in Vanilla, anyways, just two separate arguments)

**Comment by Raidobw2** [comment] 2022-08-06 06:56
Looks fine now after the PR and code
![image](https://user-images.githubusercontent.com/17010632/183238114-6cca27eb-fd7c-4f9c-bd96-82ea77e9a6a9.png)
I'm on `ftb-ranks-forge-1605.1.6-build.33.jar` for this test. Since that looks solved, I'll close this issue

**Closed by Raidobw2** 2022-08-06 06:56 UTC
Labels: api: Forge, FTB Ranks, MC 1.16+, 1: Bug
