### ISSUE TITLE
[Bug]: digital miner bypass protect ftbchunk

### ISSUE THREAD

**Issue by joaoespanhol** [FTBTeam/FTB-Mods-Issues#605] opened 2022-12-25 18:55 UTC
### Mod

FTB chunk

### Mod version

ftb-chunks-forge-1902.3.14-build.218.jar

### Forge / Fabric version

1.19.2-43.2.1

### What issue are you having?

When player A protects the chunk and places blocks
If player B does not have access to that protected chunk, use the digital miner filter, you can steal the player's base.

![image](https://user-images.githubusercontent.com/22871432/209479180-96989dfd-e0b1-46d3-a96e-f96d0d96a9f9.png)

### Steps to reproduce

1. protect chunk
![image](https://user-images.githubusercontent.com/22871432/209479180-96989dfd-e0b1-46d3-a96e-f96d0d96a9f9.png)
2. other player use filter mekanism digital miner
3. start

**Comment by joaoespanhol** [comment] 2023-01-07 15:14
We have been firing block break events since 1.12 if not earlier (wasn't part of the team before 1.12 and don't feel like confirming how far back it goes).

[Mekanism/src/main/java/mekanism/common/tile/machine/TileEntityDigitalMiner.java](https://github.com/mekanism/Mekanism/blob/25459b3d3ef8f25d32c9ec4c8f214a4885e221e1/src/main/java/mekanism/common/tile/machine/TileEntityDigitalMiner.java#L529)

Line 529 in [25459b3](https://github.com/mekanism/Mekanism/commit/25459b3d3ef8f25d32c9ec4c8f214a4885e221e1)

 return withFakePlayer(dummy -> !MinecraftForge.EVENT_BUS.post(new BlockEvent.BreakEvent(level, pos, state, dummy))); 
So going to go with an fab chunks bug unless they can explain why it is on our end, as it seems like they just aren't listening to the event.

@desht  reopen ticket please

**Comment by desht** [comment] 2023-01-07 18:01
@joaoespanhol thanks, missed that when I looking through the source.  Chunks most definitely does listen to the event though, so some debugging will be required.  Have you set Chunks to allow fake players to bypass protection?

**Comment by joaoespanhol** [comment] 2023-01-07 18:27
> @joaoespanhol thanks, missed that when I looking through the source. Chunks most definitely does listen to the event though, so some debugging will be required. Have you set Chunks to allow fake players to bypass protection?

no.

perms player is default.

**Comment by desht** [comment] 2023-01-08 10:24
I can't reproduce your problem then.  I set up a Digital Miner in a protected area with an Iron Ore filter, and ensured that "Allow Fake Players" was switched off in the Teams settings:

![image](https://user-images.githubusercontent.com/736831/211190951-6fb98c55-18d0-47f3-8fd7-51e66959967d.png)

The miner found 0 zero blocks to mine.

I then switched "Allow Fake Player" to True, and restarted the miner.  It started mining up Raw Iron chunks as expected.

**Comment by joaoespanhol** [comment] 2023-01-08 11:10
but then the fingerprint does not work in unprotected areas.

The issue is that a digital miner breaks other players' protected areas.

> I can't reproduce your problem then. I set up a Digital Miner in a protected area with an Iron Ore filter, and ensured that "Allow Fake Players" was set to False in the Teams settings:
> 
> ![image](https://user-images.githubusercontent.com/736831/211190951-6fb98c55-18d0-47f3-8fd7-51e66959967d.png)
> 
> The miner found 0 zero blocks to mine.
> 
> I then switched "Allow Fake Players" to True, and restarted the miner. It started mining up Raw Iron chunks as expected.

but then the fingerprint does not work in unprotected areas.

The issue is that a digital miner breaks other players' protected areas.

**Comment by desht** [comment] 2023-01-08 13:17
> but then the fingerprint does not work in unprotected areas.

I don't know what you mean by that.  What is a "fingerprint" in this context?

**Comment by desht** [comment] 2023-02-15 11:44
Fixed in latest FTB Chunks release. You should review your current team properties setttings, and ensure that:
* "Allow All Fake Players" is **false**
* "Allow Fake Players by Player ID" is **true**
* "Allied Fake Player Names/IDs" is empty if possible (this is only here to support mods who don't use real player ID's in their fake players; these mods can't be 100% safely used with claim protection)

**Closed by desht** 2023-02-15 11:44 UTC
Labels: api: Forge, FTB Chunks, state: Fixed in Dev 🛠️, MC 1.19+, 1: Compatibility
