### ISSUE TITLE
[Bug]: game crashes when creating a quest from an item

### ISSUE THREAD

**Issue by Rextrere800** [FTBTeam/FTB-Mods-Issues#470] opened 2022-09-21 00:42 UTC
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1802.3.8-build.106

### Forge / Fabric version

1.18.2 0.14.8

### What issue are you having?

When I create a quest from an item the game crashes.

### Crashlogs

#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\mprie\AppData\Roaming\.minecraft\crash-reports\crash-2022-09-20_21.30.59-client.txt
[21:30:95] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: mouseReleased event handler
	at net.minecraft.class_437.method_25412(class_437.java:497)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: dev/architectury/hooks/tags/TagHooks
	at dev.latvian.mods.itemfilters.api.ItemFiltersAPI.<clinit>(ItemFiltersAPI.java:25)
	at dev.ftb.mods.ftbquests.quest.task.ItemTask.getValidDisplayItems(ItemTask.java:123)
	at dev.ftb.mods.ftbquests.quest.task.ItemTask.getAltIcon(ItemTask.java:142)
	at dev.ftb.mods.ftbquests.quest.QuestObjectBase.getIcon(QuestObjectBase.java:287)
	at dev.ftb.mods.ftbquests.quest.Quest.getAltIcon(Quest.java:430)
	at dev.ftb.mods.ftbquests.quest.QuestObjectBase.getIcon(QuestObjectBase.java:287)
	at dev.ftb.mods.ftbquests.gui.quests.QuestButton.<init>(QuestButton.java:48)
	at dev.ftb.mods.ftbquests.gui.quests.QuestPanel.addWidgets(QuestPanel.java:131)
	at dev.ftb.mods.ftblibrary.ui.Panel.refreshWidgets(Panel.java:62)
	at dev.ftb.mods.ftblibrary.ui.Panel.refreshWidgets(Panel.java:71)
	at dev.ftb.mods.ftblibrary.ui.BaseScreen.initGui(BaseScreen.java:80)
	at dev.ftb.mods.ftblibrary.ui.ScreenWrapper.method_25426(ScreenWrapper.java:31)
	at net.minecraft.class_437.method_25423(class_437.java:389)
	at net.minecraft.class_310.method_1507(class_310.java:993)
	at dev.ftb.mods.ftblibrary.ui.BaseScreen.openGui(BaseScreen.java:340)
	at dev.ftb.mods.ftbquests.client.ClientQuestFile.openQuestGui(ClientQuestFile.java:134)
	at dev.ftb.mods.ftbquests.client.FTBQuestsClientEventHandler.onCustomClick(FTBQuestsClientEventHandler.java:103)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$5.handleInvocation(EventFactory.java:152)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy132.act(Unknown Source)
	at dev.ftb.mods.ftblibrary.util.ClientUtils.handleClick(ClientUtils.java:148)
	at dev.ftb.mods.ftblibrary.ui.BaseScreen.handleClick(BaseScreen.java:387)
	at dev.ftb.mods.ftblibrary.ui.Widget.handleClick(Widget.java:187)
	at dev.ftb.mods.ftblibrary.sidebar.SidebarButton.onClicked(SidebarButton.java:156)
	at dev.ftb.mods.ftblibrary.integration.REIIntegration$SidebarButtonEntry.doAction(REIIntegration.java:168)
	at me.shedaniel.rei.impl.client.favorites.DelegatingFavoriteEntryProviderImpl.doAction(DelegatingFavoriteEntryProviderImpl.java:81)
	at me.shedaniel.rei.impl.client.gui.widget.region.RegionEntryWidget.doAction(RegionEntryWidget.java:130)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25406(EntryWidget.java:549)
	at net.minecraft.class_4069.method_20083(class_4069.java:41)
	at java.base/java.util.Optional.filter(Optional.java:218)
	at net.minecraft.class_4069.method_25406(class_4069.java:41)
	at me.shedaniel.rei.impl.client.gui.widget.favorites.FavoritesListWidget.method_25406(FavoritesListWidget.java:309)
	at net.minecraft.class_4069.method_20083(class_4069.java:41)
	at java.base/java.util.Optional.filter(Optional.java:218)
	at net.minecraft.class_4069.method_25406(class_4069.java:41)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$17(RoughlyEnoughItemsCoreClient.java:369)
	at net.minecraft.class_312.handler$zhl000$onGuiMouseReleased(class_312.java:633)
	at net.minecraft.class_312.method_1605(class_312.java)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	... 15 more
Caused by: java.lang.ClassNotFoundException: dev.architectury.hooks.tags.TagHooks
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 56 more

AL lib: (EE) alc_cleanup: 1 device not closed
Here I am!
[VersionManager] Refreshing versions locally...
[Version:fabric-loader-0.14.8-1.18.2] Resolving...
[Version:fabric-loader-0.14.8-1.18.2] Inherits from 1.18.2
[Version:fabric-loader-0.14.9-1.19.2] Resolving...
[Version:fabric-loader-0.14.9-1.19.2] Inherits from 1.19.2
[VersionManager] Versions has been refreshed (70 ms)
[Launcher] Minecraft closed with exit code: -1
flush now
[Launcher] Launcher exited.
[Launcher] [Crash] Found crash report file: C:\Users\mprie\AppData\Roaming\.minecraft\crash-reports\crash-2022-09-20_21.12.41-client.txt
[Crash] Found crash report file: C:\Users\mprie\AppData\Roaming\.minecraft\crash-reports\crash-2022-09-20_21.12.41-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\mprie\AppData\Roaming\.minecraft\crash-reports\crash-2022-09-20_21.30.59-client.txt
[Crash] Found crash report file: C:\Users\mprie\AppData\Roaming\.minecraft\crash-reports\crash-2022-09-20_21.30.59-client.txt
flush now

### Steps to reproduce

1. I created a chapter
2. I edited this chapter
3. I putted an icon and subtitle
4. I set false the always invisible 
5. I set in default the quest shape
6. I accepted the quest
7. When I right clicked the button at the center appeared the menu with different options
8. I clicked item
9. I configured the item and the quantity
10. I accepted and it crashed

**Comment by Raidobw2** [comment] 2022-09-21 09:05
Hi thanks for the report, could you post your version of Architectury as well? Thanks

**Comment by Rextrere800** [comment] 2022-09-21 14:15
I have the version architectury 4.9.83 and item filters 1801.2.6 build 17.

**Comment by desht** [comment] 2022-10-05 09:01
The problem is your ItemFilters version, which is out of date for the version of Architectury you're using.

Item Filters 1802.2.7 build 29 is what's currently built against in dev, so that will definitely work (I've just verified that).  However newer versions (Item Filters 1802.2.8 is out) are also likely to be OK.  Can you please test with one of these and let us know?

**Comment by Rextrere800** [comment] 2022-10-28 19:04
I tested with the item filters 1802.2.7 build 33 and it worked.

**Comment by MichaelHillcox** [comment] 2023-04-08 09:20
No reply, closing

**Closed by MichaelHillcox** 2023-04-08 09:20 UTC
Labels: api: Fabric, FTB Quests, MC 1.18+, 1: Bug, state: Awaiting Reply :speaking_head:
