### ISSUE TITLE
[Bug]: Block Interaction Mode: In a public state, other users can place blocks and duplicate them.

### ISSUE THREAD

**Issue by sungho955** [FTBTeam/FTB-Mods-Issues#673] opened 2023-02-07 08:08 UTC
### Mod

ftb-chunks-fabric-

### Mod version

ftb-chunks-fabric-1802.3.13-build.234

### Forge / Fabric version

fabric 1.18.2 - 0.14.12

### What issue are you having?

1. This is a personal mod pack.

2. setting
![2023-02-07_16 57 53](https://user-images.githubusercontent.com/68801535/217185798-8aa39202-85bf-4f3a-9d54-83d9f1f8ce80.png)

3. modlist [curse forge]
[1.18.2 (1).zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/10672786/1.18.2.1.zip)

4. Block Interaction Mode: In a public state, other users can place blocks and duplicate them.
https://youtu.be/6ZKIZz3nZFc

### Steps to reproduce

1. setting all privata

2. only block interact mode : public

3. Non-party users can interact and place blocks

**Comment by desht** [comment] 2023-02-07 10:27
Dupe of #315 - will be fixed in next FTB chunks release

**Closed by desht** 2023-02-07 10:27 UTC
Labels: api: Fabric, FTB Chunks, 1: Bug

**Comment by sungho955** [comment] 2023-02-07 11:48
> Dupe of #315 - 다음 FTB 청크 출시에서 수정될 예정입니다.

Thanks! Are there any scheduled deadlines?

**Comment by desht** [comment] 2023-02-07 15:19
Within a few days probably.

**Comment by sungho955** [comment] 2023-03-05 06:44
I'm sorry you seem busy.
I confirmed that the dev version was uploaded.
A lot of time has passed, but is there a problem with coming up to the main?

**Comment by desht** [comment] 2023-03-05 09:24
My apologies for the delay on this; I will do my best to get this released in the next couple of days.
