### ISSUE TITLE
[Bug]: Quest titles can not be colored as of 1.21

### ISSUE THREAD

**Issue by chorbintime** [FTBTeam/FTB-Mods-Issues#1272] opened 2024-07-14 14:37 UTC
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-2100.1.3

### Forge / Fabric version

1.21 Fabric 0.16.0

### What issue are you having?

When creating a quest, you are able to set a colored title using Minecraft's color codes. 

In all previous iterations of FTBQuests for older Minecraft versions, the colored title would show at the top of the quest window. 

In the 1.21 Fabric release of FTBQuests, the colors no longer show.      

Video: https://has-cool.pics/chorb/tAlaJqN

### Steps to reproduce

1.  Create a quest
2. Give it a color coded title
3. Click on the quest
4. Observe the lack of color

**Comment by desht** [comment] 2024-07-15 10:38
Can't reproduce this.  Using color codes in quest titles works fine here:

![image](https://github.com/user-attachments/assets/c4b437f1-a88d-443b-a723-a88795181a17)

![image](https://github.com/user-attachments/assets/dd112040-f02b-4496-aaad-3430b725adbf)

**Comment by chorbintime** [comment] 2024-07-15 11:48
As the video shows, the issue only happens when you click on the quest and open the screen that shows the quest tasks & rewards. The hover tooltip works completely fine.

**Comment by desht** [comment] 2024-07-15 12:34
Ah, sorry, missed that. Yep, there's a problem there, I'll take a look.

**Comment by desht** [comment] 2024-07-19 10:53
Fixed in 2100.1.4

**Closed by desht** 2024-07-19 10:53 UTC
Labels: FTB Quests, state: Fixed in Dev 🛠️, 1: Bug
