### ISSUE TITLE
[Bug]: Crash after connecting quests

### ISSUE THREAD

**Issue by TQCnoARosto** [FTBTeam/FTB-Mods-Issues#775] opened 2023-04-29 12:24 UTC
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.13-build.219

### Forge / Fabric version

Forge - 43.2.8

### What issue are you having?

The game crashes after connecting (via dependencies) two quests with each other.

### Crashlogs

https://pastebin.com/zw3ppycj

### Steps to reproduce

![Screenshot 2023-04-29 141955](https://user-images.githubusercontent.com/43849125/235302226-008a9c54-6995-4411-8ddb-42805f211abe.png)

As you can see Coal has among the dependencies the Furnace, but if i add to the Funrnace's dependencies the coal, the game crashes.

Also, after you restart Minecraft game stil crashes if you open the chapter with conneced quest, you have to delete one of the dependencies manually in the mod config.

**Comment by desht** [comment] 2023-04-29 13:12
That is correct, circular dependencies are not permitted.  Did you do this through the GUI (it should prevent this), or by editing the quest file directly?

**Comment by TQCnoARosto** [comment] 2023-04-29 14:03
No, the bug occurred after i made some circular dependencies because i was reorganizing some quests through the in-game gui, to avoid crashing after reopening the chapter with the circular dependency i modified the quests through the config file.

**Comment by TQCnoARosto** [comment] 2023-05-15 23:01
Here is my answer, dunno what more i can tell u about the crash:
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43849125/7cb92d8e-0bef-45b3-a5ad-2d8e4f508193)

Here's a video where my game crashes:
https://drive.google.com/file/d/1T7eL2j19IA7gYHKo-S4c--OLO88UBss1/view?usp=sharing

Here's the crash report:
https://bytebin.lucko.me/4wsvIbBH0B

**Comment by desht** [comment] 2023-05-16 07:02
OK, so it did happen through the GUI - sorry I wasn't clear on that. The GUI should disallow this - there is dependency validation code in there but it looks like it's missing this for some reason.  I will investigate.

**Comment by desht** [comment] 2023-05-16 10:47
OK, I was able to reproduce your problem, so I will get a fix in for that.

However, you do add dependencies in a very inefficient way - it's much quicker and easier to select a quest (Ctrl+click), then right click the other quest and select "Add select quest as dependency" or "Add as dependency to selected quest", depending on which way the dependency should go. That method also properly validates loops.

**Comment by TQCnoARosto** [comment] 2023-05-18 19:16
Ah i didn't know that, thanks for the advice.

I've just started my first modpack and i'm not aware of many shortcuts yet.

**Comment by desht** [comment] 2023-05-19 07:18
Yeah, the docs for FTB Quests are lacking quite a bit at the moment.  But we do have a project underway to greatly improve the docs.

**Comment by desht** [comment] 2023-05-30 08:50
Fixed in latest release

**Closed by desht** 2023-05-30 08:50 UTC
Labels: FTB Quests, state: Fixed in Dev 🛠️, MC 1.19+, state: Awaiting Reply :speaking_head:
