### ISSUE TITLE
[Bug] [FTB Quests]: CTD when clicking on Key Reference button.

### ISSUE THREAD

**Issue by Sandriell** [FTBTeam/FTB-Mods-Issues#1118] opened 2024-03-14 19:54 UTC
### Mod

FTB Quests

### Mod version

ftb-quests-forge-2001.3.4

### Forge / Fabric version

1.21.1 47.2.17

### What issue are you having?

Crashed to desktop when clicking on Key Reference button.

### Crashlogs

https://gist.github.com/Sandriell/1ed98972996db17ddf5d0094c92a2f69

### Steps to reproduce

Click on the Key Reference button

**Comment by desht** [comment] 2024-03-15 15:27
I can't reproduce this myself, but I'll add some extra checks to the code to prevent the NPE.

**Comment by desht** [comment] 2024-03-18 15:04
Fixed in 2001.3.5 release

**Closed by desht** 2024-03-18 15:04 UTC
Labels: FTB Quests, 1: Bug

**Comment by Sandriell** [comment] 2024-03-18 23:40
Thanks!
