### ISSUE TITLE
[Bug]: FTB Chunks: 2 Bugs (Stuck on siting) (items in itemframes)

### ISSUE THREAD

**Issue by suerion** [FTBTeam/FTB-Mods-Issues#652] opened 2023-01-25 15:40 UTC
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric-1902.3.14-build.218

### Forge / Fabric version

1.19.2 Fabric 0.14.12

### What issue are you having?

Hey, we had two Bugs found on the actuall Version for 1.19.2

1st: we could remove items from an itemframe and the itemframes itself from an claimed chunk.
https://youtu.be/-MMCYMlV6TQ

2nd: with exline's furniture mod, you could sit in an claimed  chunk, but you does not sit on it, you are stuck on chairs and could only look in one direction,
https://www.curseforge.com/minecraft/mc-mods/exlines-furniture
https://youtu.be/_y4P9JTgxWs 

### Steps to reproduce

1. Try to sit on an Chair or furniture from furniturs Mods

2. Try to remove the itemframes or items from itemframes

**Comment by desht** [comment] 2023-01-25 17:06
Please show your team settings, specifically the chunk protection settings you're using.

Also - "Admin Team".  Are you all op-level users?  Do you have extra protection bypass permissions?

**Comment by suerion** [comment] 2023-01-25 18:33
Hey 
![grafik](https://user-images.githubusercontent.com/55131959/214651741-e4837c50-05dc-435f-9f52-2409af5dac9e.png)

We don't have allies,

Admin Team are all OP Level Users without bypassing permissions

**Comment by desht** [comment] 2023-01-26 13:32
Thanks for that.

* The Item Frame issue is something that will be fixed in Chunks (it currently doesn't protect against entities being left-clicked)
* I can't see how the furniture issue is Chunks-related; Chunks just permits or prevents blocks from being interacted with.  It does nothing to entities beyond that - it doesn't do anything to prevent players looking around for example.  Since that furniture mod is closed-source, I can't do much more investigation, so I suggest you speak with the author of that mod.

**Comment by suerion** [comment] 2023-01-26 16:36
Hey @desht thanks for the fixing of the itemframes.

Thanks, i will write them

**Comment by desht** [comment] 2023-01-26 18:02
Does the furniture mod work OK for you in unclaimed chunks?

**Comment by suerion** [comment] 2023-01-26 18:07
Yes, it work, also in my own claimed chunks, only in an other claimed chunk the problem is given

**Comment by desht** [comment] 2023-01-27 08:37
I did some more testing with those conditions: in a chunk claimed by another user, and no bypass permission.  I was able to sit on one of the mod's chair without any trouble, and look around as expected.  So I can't reproduce that problem in a test instance with Chunks and Exline's Furniture Mod. There might be some other mod in your pack messing things up.

**Comment by desht** [comment] 2023-03-15 09:26
Closing this.  Item Frame (and other entity) protection is now in FTB Chunks.  Other issues here do not appear to be Chunks-related.

**Closed by desht** 2023-03-15 09:26 UTC
Labels: api: Fabric, FTB Chunks, MC 1.19+, 1: Bug, state: Awaiting Reply :speaking_head:
