### ISSUE TITLE
[Bug]: Crash when open quest tab

### ISSUE THREAD

**Issue by BlackAures1** [FTBTeam/FTB-Mods-Issues#611] opened 2022-12-29 14:56 UTC
### Mod

 ftb quests

### Mod version

ftb-quests-forge-1802.3.11-build.151

### Forge / Fabric version

1.18.2 40.1.92

### Modpack & version

https://www.curseforge.com/minecraft/modpacks/play-as-dragon

### What issue are you having?

When you try to open a list of quests on J game freezes and crashes.

### Crashlogs

[crash-2022-12-29_17.49.34-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10320059/crash-2022-12-29_17.49.34-client.txt) FULL HERE

```
at dev.ftb.mods.ftbquests.client.FTBQuestsClientEventHandler.onKeyEvent(FTBQuestsClientEventHandler.java:135) ~[ftb-quests-forge-1802.3.11-build.151.jar%23123!/:1802.3.11-build.151] {re:classloading}
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?] {re:mixin}
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.10.88-forge.jar%2363!/:?] {re:classloading}
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-4.10.88-forge.jar%2363!/:?] {re:classloading}
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%2329!/:?] {}
	at jdk.proxy3.$Proxy105.tick(Unknown Source) ~[?:?] {}
	at dev.architectury.event.forge.EventHandlerImplClient.event(EventHandlerImplClient.java:54) ~[architectury-4.10.88-forge.jar%2363!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_745_EventHandlerImplClient_event_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:916) ~[forge-1.18.2-40.1.92-universal.jar
```

### Steps to reproduce

Press J and it crash

### Anything else to note?

Thank for you mod. It is very cool!

**Comment by desht** [comment] 2023-01-03 13:30
Does this happen everytime you run the instance?  And are you running in offline mode?

**Comment by BlackAures1** [comment] 2023-01-03 16:15
Yes, singleplayer. It was an isolated crash. After that, neither in the new worlds nor in the old ones this problem did not appear. If it's nothing serious, we can just close the ticket.

**Comment by desht** [comment] 2023-01-04 11:28
Thanks.  It is an issue we're aware of, but due its unpredictable nature (and being hard to reproduce) we have yet to track down the root cause.  I'll close this, since there are related issues open for this problem.

**Closed by desht** 2023-01-04 11:28 UTC

**Comment by BlackAures1** [comment] 2023-01-04 16:08
It's okay, I know these bugs are hard to keep track of, but there really wasn't any more information. I was just creating another world to test and this crash happened. If I get another crash I can send logs and debug, but at the moment these files are already deleted.

Thank you all for a great mod!
