### ISSUE TITLE
[Bug]: Crash on selecting "topography" general setting in FTB Chunks map (ATM6:To the Sky)

### ISSUE THREAD

**Issue by Trisscar05** [FTBTeam/FTB-Mods-Issues#78] opened 2021-10-09 08:05 UTC
### Mod

FTb Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.57

### Forge / Fabric version

1.16.5 36.2.6

### Modpack & version

All The Mods 6: To the Sky

### What issue are you having?

In looking for a way to show plants instead of just farmland, I turned on the general setting "topography" after pressing "M" to access the fullscreen map and related gizmos. On exiting the settings menu for the map, the game froze and then crashed. On reloading the world from the launcher, the game froze at the point before it would normally display the mini map (also before loading in blocks that do not have unusual rendering, which meant all of the cobblestone was invisible for example), and then crashed.

This modpack has been slightly modified, mods added are Pams ~Trees~ and ~Food Extended~, as well as Minecolonies.

### Crashlogs

https://pastebin.com/psxUbUyu

### Steps to reproduce

See issue description.

### Anything else to note?

The error is mentioning a mod that appears to be this one:
https://www.curseforge.com/minecraft/mc-mods/architectury-forge
Which is interesting, and probably means that if the mods that were added aren't affecting it, then this might be a modpack wide problem. I've seen more questions about accessing the map settings in game than I have anything else, so it seems mildly likely that people just aren't changing this setting very often.

I have looked around to see if I can turn off the topography setting without loading the world itself, and so far all I've found is either possibly playerdata, or three number files that contain this:
{
	max_claim_chunks: 500
	max_force_load_chunks: 25
	extra_claim_chunks: 0
	extra_force_load_chunks: 0
	chunk_load_offline: true
	chunks: { }
}
Which does not seem to be what I'm looking for. I might attempt to simply remove the mod from the pack to see if I can un-soft-lock myself.
If possible and reasonable though, I do think it would be a nice feature to be able to change minimap settings with a config file or something outside the game, without having to find a way to pry apart the player file itself. Simply because I can imagine this being an issue later due to accidental shenaniganry on players, modders, or even server owners parts.
Buuuuut, if taking out the mod and then putting it back in again after a save works then that's probably not necessary so... eh.

**Comment by Trisscar05** [comment] 2021-10-09 08:35
Update: Tested taking Chunks out, game works just fine without it. Adding it back in after saving however crashes the same way.

**Comment by Trisscar05** [comment] 2021-10-10 00:00
2nd Update: Closed the launcher for the night (ATLauncher), and came back in the morning. Loading the game once without FTB Chunks caused the game to misplace Architecturey, to the point that the error message during loading was "Where's Architecturey?", which caused the game to fail to load.
Loading it again without closing the launcher, but this time with Chunks enabled again, allowed the game to get to the main menu, however the issue of crashing on loading the world remained.
Loading it for a third time without closing the launcher, this time with Chunks disabled again, results in a playable saved game with no minimap.

**Comment by Raidobw2** [comment] 2021-10-19 05:17
I have absolutely no idea if this would work to be honest since I've only heard of it, but you should be able to do this:
- Creating a new world and changing the config in there.
- Going into `local/ftbchunks/client-config.snbt` and changing the values there. They are well labeled so that should be no problem.
As said earlier, this might not fix it, but you can try.

**Comment by Raidobw2** [comment] 2021-10-21 08:30
Yay haha. No problem. :)

**Comment by desht** [comment] 2022-11-15 14:48
I know this is about a year old now, but are you in a position to test this with a more recent version of FTB Chunks? There have been several revisions to the mod since this issue, and I can't reproduce any crashes using mode=topography in the current release.

If not, I think it's best to close this issue; any new crashes can be raised as a new issue (in particular, the stacktrace line numbers don't line up with the current code, making debugging difficult).

**Comment by Trisscar05** [comment] 2022-11-16 05:45
Seems fine to me, currently buried in college stuff. Luck with things!

**Comment by desht** [comment] 2022-11-16 08:18
And good luck to you!

Going to close this, feel free to reopen if you see this behaviour again...

**Closed by desht** 2022-11-16 08:18 UTC
Labels: FTB Chunks, MC 1.16+, prio: Medium ◓, 1: Bug
