### ISSUE TITLE
[Bug]: Clicking to accept TPA request does not work 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [FTBTeam/FTB-Mods-Issues#901] opened 2023-08-05 23:19 UTC
### Mod

FTB Essentials  

### Mod version

2001.1.2

### Forge / Fabric version

NeoForge 47.1.62

### What issue are you having?

Can't accept TPA

### Steps to reproduce

1. get a tpa
2. click accept
3. get error 

### Anything else to note?

![1691277527711-Discord_E4NPJbDN7h](https://github.com/FTBTeam/FTB-Mods-Issues/assets/8102498/dd5726dd-d152-4e3c-9dc6-53e763d6a6ab)

**Comment by Rushmead** [comment] 2023-08-05 23:37
This is caused by the combination of FTB Essentials and @terrariumearth's Prometheus on the ForgeCraft server. Both mods have commands named the same and are attempting to interact with each other. Really commands should be namespaced, but that's not an issue for FTB. Essentially only fixed by having one of the mods, not both.

**Comment by manmaed** [comment] 2023-08-05 23:52
i feel like we should do namespaced commands to fix it

**Closed** 2023-09-07 22:41 UTC
Labels: api: Forge, FTB Essentials, state: Other Mod, 1: Bug, 1: Compatibility

**Comment by desht** [comment] 2023-09-08 08:20
Just to note: in future versions of FTB Essentials, we plan to have a top-level `/ftbe` command and all existing commands beneath it (e.g. `/ftbe tpa ...`). This will eliminate any ambiguity.

There will likely also be aliases added (`/tpa` -> `/ftbe tpa`) IFF there aren't any clashing mods loaded. But `/ftbe tpa` will become the recommended method for any automated execution (command blocks, mcfunctions, etc.)
