### ISSUE TITLE
[Bug]: Smeltery

### ISSUE THREAD

**Issue by DunnBerry1224** [FTBTeam/FTB-Mods-Issues#1409] opened 2024-12-03 19:26 UTC
### Mod

Tickers' Construct 2.0

### Mod version

Update 2.0

### NeoForge / Forge / Fabric version

None

### What issue are you having?

In the bedrock version of Tinkers construct the smeltery controller will not interact with ore, raw ore, ingots, or blocks of any material you try to imput. Also blaze lava and lava both have the same texture applied when in the sear tank.

### Steps to reproduce

Build smeltery, follow directions provided in mighty smeltery book.

**Comment by WyFryMU** [comment] 2024-12-03 22:03
Duplicate of https://github.com/FTBTeam/FTB-Bedrock-Issues/issues/143
For future reference, please post bedrock issues in FTB Bedrock Issues.

**Closed** 2024-12-04 00:47 UTC
Labels: 1: Bug
