### ISSUE TITLE
[Bug]: Power Pots Mk3/4 dupe issue

### ISSUE THREAD

**Issue by TomBombadil4Real** [FTBTeam/FTB-Mods-Issues#646] opened 2023-01-23 22:43 UTC
### Mod

FTB Power Pots

### Mod version

ftb-power-pots-forge-1605.1.2-build.16

### Forge / Fabric version

1.16.5 36.2.35

### Modpack & version

Sky Capsule Project 1.0.1

### What issue are you having?

When piping out of Mk1/2 power pots with any of the mods we've tested (pipez, xnet) the extraction seems to work just fine without needing to add a storage container below it. But if you try to auto pipe out of mk3/4 pots the plant gets stuck on 100% but continuously extracts essence until the pot is broken (without the need for the plant to go through the growing process, filling up a drawer in a matter of seconds). Placing a storage container of any sort below the mk3/4 allows the pot to function normally, it's only when you try to auto pipe/extract from the pots themselves. 

### Steps to reproduce

Place a mk1 or mk2 pot down, power it and extract using a pipe or other means to a storage container (the pipe is connected to the pot directly, not the storage container). It should process and extract fine. Then place a mk3 or mk4 down and try to do the same thing (pipe directly out of it) and the plant should get stuck on 100% but continue to extract until you break the power pot.

**Comment by H13n12** [comment] 2023-01-31 16:21
i am pretty sure the problem is caused by the fact that the mk3/4 power pot produces more than 1 stack of item and most mods' pipes tend to only have a single item slot as a buffer. i could be very wrong though.

**Comment by desht** [comment] 2023-02-01 09:05
I think you might need to provide some more specific instructions to reproduce the problem here, since I can't make it happen.  I have a Mk4 Power Pot, with a Pipez pipe extracting from it into a couple of Mekanism bins.  (Tried Pipez with differing levels of pipe upgrade, and also tried Mek Logistical Transporters).  It's not getting stuck at 100% and continuously extracting as you described - once the pot's internal inventory is full, it just stops growing and sits at 0%.

![2023-02-01_09 04 53](https://user-images.githubusercontent.com/736831/215998787-d79a6505-d3a2-4b16-a1b4-256437076c5d.png)

**Comment by TomBombadil4Real** [comment] 2023-02-01 16:02
Hey Desht thanks for writing back. Some further clarification, I forgot that we upped the production values of the pots when we first added them to the pack so they are a bit higher than default values (i've attached a txt file with the config)
[ftb-power-pots-common.toml.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/10558871/ftb-power-pots-common.toml.txt)

The test seed is Diamond from Mystical Agriculture in the recording but it does the same with wheat crop, I screenrecorded so you can see what is happening. https://www.xbox.com/en-US/play/media/RMP9BRX2VS

In the recording there's a creative energy cube to power it, then the mk4 pot with pipez connected to the bottom (netherite upgrade so it's extracting 64 items per tick) and the 3 black hole units to show how quickly it goes up.

**Comment by TomBombadil4Real** [comment] 2023-02-03 17:21
Another quick follow up to this, wanted to test things out not in our Sky Capsule Project pack to see if there was maybe something conflicting in the pack itself. 

Steps I took

-Create new modded profile for 1.16.5 with Forge v 36.2.35
-Add the following Mods

BookShelf-Forge-1.16.5-10.4.32
BotanyPots-1.16.5-7.1.39
ftb-power-pots-forge-1605.1.2-build.16
jei-1.16.5-7.7.1.152
Mekanism-1.16.5-10.1.2.457
pipez-1.16.5-1.2.15
theoneprobe-1.16-3.1.7

Start up a world and place down Creative Energy Cube, attach the mk4 to it, pipe out from the bottom with netherite upgrade to Ultimate Bins. It processes as expected. Remove the dirt and the seed from the power pot. Exit the game, Adjust the values in the config to be what we have in SCP (16, 64, 128, and 256). Load back in and replace the dirt and seed and it goes to 100% and does the continuous extraction of wheat. So it seems to be tied to the adjusting of values for itemsPerOutput

**Comment by desht** [comment] 2023-02-03 17:58
OK, thanks.  Should be enough to track the issue down, hopefully.

**Comment by desht** [comment] 2023-02-08 08:39
Sorry for the delay, but I did some testing this morning.  As far as I can see, this is working as intended.

* Power pots have a 6-slot internal inventory.
* You have Mk4 Power Pots set to produce 256 items/tick, filling that inventory in less than 2 ticks
* Pipez with the Ultimate Pipe Upgrade can extract 64 items/tick, so clearly slower than the pot is producing
* The pot is producing a net excess of 3 stacks/tick, so it will obviously never empty.
* 64 items/tick, or 1280 items/second, goes to the Ultimate Bin, which is what I'm seeing

So I don't see how this is any way bugged.  You asked for too many items/tick and you got it :)

**Comment by desht** [comment] 2023-02-08 11:49
There's a dev build available at https://maven-admin.ftb.dev/repository/maven-public/dev/ftb/mods/ftb-power-pots-forge/1605.1.3-build.18/ftb-power-pots-forge-1605.1.3-build.18.jar , not sure if you're in a position to test it?

I should note that with 256 items/tick being produced, any crops which drop more than one item (e.g. plant and seeds) will overfill the 6-slot internal inventory, so using pipes of any kind to directly extract is really not a good idea; there's a significant chance of outputs being voided since there's nowhere for them to go.  Much better to place a buffer chest underneath the power pot, and extract from that instead.

**Comment by TomBombadil4Real** [comment] 2023-02-08 15:19
Thanks desht, I should have some time this afternoon to test out the dev build. I didn't realize the output was per tick, the pot takes a couple seconds to process, I thought the 128/256 specified in the config was per completion operation for the mk3/4 so the pipe would have a few seconds to extract the full buffer. I 100% agree about the buffer storage below it and that's how i always do it but our players seem to like to cheese the system wherever they can lol.

**Comment by TomBombadil4Real** [comment] 2023-02-08 15:42
> There's a dev build available at https://maven-admin.ftb.dev/repository/maven-public/dev/ftb/mods/ftb-power-pots-forge/1605.1.3-build.18/ftb-power-pots-forge-1605.1.3-build.18.jar , not sure if you're in a position to test it?
> 
> I should note that with 256 items/tick being produced, any crops which drop more than one item (e.g. plant and seeds) will overfill the 6-slot internal inventory, so using pipes of any kind to directly extract is really not a good idea; there's a significant chance of outputs being voided since there's nowhere for them to go. Much better to place a buffer chest underneath the power pot, and extract from that instead.

Just remoted in to test it out real quick for you. And sure enough the Dev build does let it process correctly even with the adjusted outputs and resets the progress bar so it functions as it should.

**Comment by desht** [comment] 2023-02-09 12:01
Excellent, thanks for testing.  I'll try to get a new release out in the next day or two.

**Comment by desht** [comment] 2023-02-09 12:03
> I didn't realize the output was per tick

Sorry, poor wording on my part.  Yes, it is per growth-completed operation, not per tick.  But when the progress wasn't correctly being reset, it became 256/tick...

**Comment by TomBombadil4Real** [comment] 2023-02-09 15:20
Perfect thank you so much.  And that makes sense about the /tick. Just wanted to make sure I wasn't misunderstanding the config and flooding it with 80 stacks per second if that was the case lol.  Cheers!

**Comment by desht** [comment] 2023-02-14 09:31
Fixed in v1605.1.3, just released on Curseforge.

**Closed by desht** 2023-02-14 09:31 UTC
Labels: api: Forge, MC 1.16+, state: Fixed in Dev 🛠️, FTB Power Pots
