### ISSUE TITLE
[Bug]: Break Distance

### ISSUE THREAD

**Issue by TookUrSweetRoll** [FTBTeam/FTB-Mods-Issues#380] opened 2022-07-25 09:11 UTC
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-forge-1802.3.3-build.55

### Forge / Fabric version

1.18.2  40.1.68

### What issue are you having?

Its a small thing, but there is a discrepancy in the distance from vanilla block breaking to activating the ultimine. Below are my recorded X values from F3.

Target Block: X 5.3
Vanilla break: X 9.375
Ultimine break: X 8.993

### Steps to reproduce

See above

**Comment by berryh** [comment] 2022-10-31 12:44
Can confirm, the reproduction is also rather simple: hold the Ultimine key and slowly walk up to a block. You'll see the default black box outline (from Minecraft itself) appear about half a block before the Ultimine overlay renders. Trying to mine from that half a block also results in just the one block being mined.

I took a look at the source, and the problem line seems to be:
`return player.pick(player.isCreative() ? distance : distance - 0.5D, 1F, false);`
which is in `dev/ftb/mods/ftbultimine/FTBUltiminePlayerData.java:43`. The subtraction is what causes this issue and removing it fixes the situation. But, this check and subtraction has been there since the beginning of this mod and I can't find a reason for it. Maybe I'm missing something? Or was this in place due to some old bug for example?

**Comment by desht** [comment] 2023-01-27 16:35
Will also be fixed in next 1.19 release, coming soon.

**Comment by desht** [comment] 2023-05-11 10:34
Fixed in 1902.4.0 release

**Closed by desht** 2023-05-11 10:34 UTC
Labels: api: Forge, FTB Ultimine, state: Fixed in Dev 🛠️, MC 1.18+, 1: Bug
