### ISSUE TITLE
[Bug]: FTB Quests (Forge) Right click crash

### ISSUE THREAD

**Issue by Joshernoob** [FTBTeam/FTB-Mods-Issues#597] opened 2022-12-16 19:11 UTC
### Mod

FTB Quests (Forge)/ FTB Library (Forge)

### Mod version

ftb-quests-forge-1902.4.3-build.140/ ftb-library-forge-1902.3.10-build.162

### Forge / Fabric version

43.2.0

### Modpack & version

Chunkblock 0.1.6 / Dev Version

### What issue are you having?

When editing quest right click works normal as intended but once you disable edit mode and right click on a quest it will crash out to the main menu (this may be thanks to Not Enough Crashes).

according to Not Enough Crashes (Forge) this is do to both FTB Quests (Forge) and FTB Library (Forge) in some way

### Crashlogs

https://pastebin.com/wuPuzCN0 

### Steps to reproduce

1 Make sure edit modes off
2 have a quest already set up
3 right click quest while edit mode off
Optional use Not Enough Crashes (Forge) to keep game open

### Anything else to note?

this may be do to Quests Additions (Forge) i'll do some testing but from what iv seen so far seem to be the mod itself

**Comment by Joshernoob** [comment] 2022-12-16 19:18
Can confirm it is not Quests Additions (Forge)

**Comment by Joshernoob** [comment] 2022-12-16 19:27
seems downgrading FTB Quests (Forge) fixes the bug for now

**Comment by emanuele246gi** [comment] 2022-12-18 10:37
I also made some time ago a post here

**Comment by desht** [comment] 2022-12-19 11:10
Already fixed in dev, next release of Quests (coming very soon) will have the fix.

**Comment by desht** [comment] 2022-12-19 11:46
Dupe of #560

**Closed by desht** 2022-12-19 11:46 UTC
