### ISSUE TITLE
[Bug]: 1.19.2: game crashed because of ghast fireball, crashes when relaunched

### ISSUE THREAD

**Issue by rMcKee1** [FTBTeam/FTB-Mods-Issues#1053] opened 2023-12-31 10:07 UTC
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.4.3-build321

### Forge / Fabric version

1.19.2 43.3.0

### Modpack & version

Custom Pack

### What issue are you having?

ghast shot fireball somewhere behind me, heard it explode, then world/client crashed and crashes instantly when i boot it up now

### Crashlogs

[https://pastebin.com/LD9kncka](url)

additionally : The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_9236_()" because the return value of "net.minecraftforge.event.entity.EntityMobGriefingEvent.getEntity()" is null

### Steps to reproduce

1.ghast shot fireball that exploded somewhere nearby

**Comment by rMcKee1** [comment] 2023-12-31 11:06
Any ideas to fix the bug are appreciated btw :)

**Comment by desht** [comment] 2024-01-02 08:46
Dupe of #1049, there will be a fix released today.

**Closed by desht** 2024-01-02 08:46 UTC
